CREATE SEQUENCE stop_id_seq
START WITH 00000001
INCREMENT BY 1
MAXVALUE 9999999;
-- stop_id, line_id, stop_name_th, stop_name_en, sequence_no, direction, is_fare_point

-- ==========================
-- Light Green Line
-- ==========================
INSERT INTO station_stop VALUES ('E1.1.1', 1, 'ชิดลม', 'Chit Lom', 1, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('CEN.1.1', 1, 'สยาม', 'Siam', 2, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.1', 1, 'ราชเทวี', 'Ratchathewi', 3, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.2', 1, 'พญาไท', 'Phayathai', 4, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.3', 1, 'อนุสาวรีย์ชัยสมรภูมิ', 'Victory Monument', 5, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.4', 1, 'สนามเป้า', 'Sanam Pao', 6, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.5', 1, 'อารีย์', 'Ari', 7, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.6', 1, 'เสนาร่วม', 'Sena Ruam', 8, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.7', 1, 'สะพานควาย', 'Saphan Khwai', 9, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.8', 1, 'หมอชิต', 'Mo Chit', 10, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.9', 1, 'ห้าแยกลาดพร้าว', 'Ha Yaek Lat Phrao', 11, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.10', 1, 'พหลโยธิน 24', 'Phahon Yothin 24', 12, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.11', 1, 'รัชโยธิน', 'Ratchayothin', 13, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.12', 1, 'เสนานิคม', 'Sena Nikhom', 14, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.13', 1, 'มหาวิทยาลัยเกษตรศาสตร์', 'Kasetsart University', 15, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.14', 1, 'กรมป่าไม้', 'Royal Forest Department', 16, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.15', 1, 'บางบัว', 'Bang Bua', 17, 'Inbound', NULL);

INSERT INTO station_stop VALUES ('N1.2.1', 1, 'บางบัว', 'Bang Bua', 1, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.2', 1, 'กรมป่าไม้', 'Royal Forest Department', 2, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.3', 1, 'มหาวิทยาลัยเกษตรศาสตร์', 'Kasetsart University', 3, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.4', 1, 'เสนานิคม', 'Sena Nikhom', 4, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.5', 1, 'รัชโยธิน', 'Ratchayothin', 5, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.6', 1, 'พหลโยธิน 24', 'Phahon Yothin 24', 6, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.7', 1, 'ห้าแยกลาดพร้าว', 'Ha Yaek Lat Phrao', 7, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.8', 1, 'หมอชิต', 'Mo Chit', 8, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.9', 1, 'สะพานควาย', 'Saphan Khwai', 9, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.10', 1, 'เสนาร่วม', 'Sena Ruam', 10, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.11', 1, 'อารีย์', 'Ari', 11, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.12', 1, 'สนามเป้า', 'Sanam Pao', 12, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.13', 1, 'อนุสาวรีย์ชัยสมรภูมิ', 'Victory Monument', 13, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.14', 1, 'พญาไท', 'Phayathai', 14, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.15', 1, 'ราชเทวี', 'Ratchathewi', 15, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('CEN.2.1', 1, 'สยาม', 'Siam', 16, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('E1.2.1', 1, 'ชิดลม', 'Chit Lom', 17, 'Outbound', NULL);

-- ==========================
-- 2-38 Line
-- ==========================
INSERT INTO station_stop VALUES ('2-38.1.1', 6, 'เดอะมอลล์บางกะปิ', 'The Mall Bangkapi', 1, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.1', 6, 'แม็คโครลาดพร้าว', 'Makro Lat Phrao', 2, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.3.1', 6, 'ซอยลาดพร้าว 142', 'Lat Phrao 142 Allay', 3, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.4.1', 6, 'ซอยลาดพร้าว 136', 'Lat Phrao 136 Allay', 4, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.5.1', 6, 'ตรงข้ามโรงพยาบาลเวชธานี', 'Opposite Vejthani Hospital', 5, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.6.1', 6, 'ซอยลาดพร้าว 130', 'Lat Phrao 130 Allay', 6, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.7.1', 6, 'ก่อนแยกลาดพร้าว 101', 'Before Lat Phrao101 Intersection', 7, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.8.1', 6, 'ซอยลาดพร้าว 126', 'Lat Phrao 126 Allay', 8, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.9.1', 6, 'ซอยลาดพร้าว 122', 'Lat Phrao 122 Allay', 9, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.10.1', 6, 'ตรงข้ามโรงพยาบาลลาดพร้าว', 'Opposite Lat Phrao Hospital', 10, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.11.1', 6, 'ตรงข้ามฟู้ดแลนด์', 'Opposite Food Land', 11, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.12.1', 6, 'ซอยลาดพร้าว 114, โรงเรียนบางกอกศึกษา', 'Lat Phrao 114 Allay', 12, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.13.1', 6, 'ซอยลาดพร้าว 112', 'Lat Phrao 112 Allay', 13, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.14.1', 6, 'ซอยลาดพร้าว 106', 'Lat Phrao 106 Allay', 14, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.15.1', 6, 'ตรงข้ามบิ๊กซีลาดพร้าว', 'Opposite Big C Lat Phrao', 15, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.16.1', 6, 'ซอยลาดพร้าว 90', 'Lat Phrao 90 Allay', 16, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.17.1', 6, 'ตรงข้ามซอยลาดพร้าว 71', 'Opposite Lat Phrao 71 Allay', 17, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.18.1', 6, 'ซอยลาดพร้าว 80', 'Lat Phrao 80 Allay', 18, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.19.1', 6, 'ตรงข้ามไปรษณีย์ลาดพร้าว', 'Opposite Post Office Lat Phrao', 19, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.20.1', 6, 'ตรงข้ามศึกษาภัณฑ์ลาดพร้าว', 'Opposite Suksaphan Lat Phrao', 20, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.21.1', 6, 'ซอยลาดพร้าว 62', 'Lat Phrao 62 Allay', 21, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.22.1', 6, 'ตรงข้ามตลาดโชคชัย 4', 'Opposite Chokchai 4 Market', 22, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.23.1', 6, 'ตรงข้ามตลาดสะพาน 2', 'Opposite Saphan 2 Market', 23, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.24.1', 6, 'โรงเรียนพิบูลอุปถัมภ์', 'Pibool Uppatham School', 24, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.25.1', 6, 'ตรงข้ามซอยภาวนา', 'Opposite Phawana Allay', 25, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.26.1', 6, 'ซอยลาดพร้าว 42', 'Lat Phrao 42 Allay', 26, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.27.1', 6, 'ซอยลาดพร้าว 40, ศิริชัยไกย่าง', 'Lat Phrao 40 Allay', 27, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.28.1', 6, 'ซอยลาดพร้าว 34', 'Lat Phrao 34 Allay', 28, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.29.1', 6, 'ตรงข้ามบ้านกลางเมือง ลาดพร้าว', 'Baan Klang Muang', 29, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.30.1', 6, 'ซอยลาดพร้าว 28', 'Lat Phrao 28 Allay', 30, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.31.1', 6, 'MRT ลาดพร้าว (ทางออก 1)', 'MRT Lat Phrao Station (Exit 1)', 31, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.32.1', 6, 'ซอยลาดพร้าว 20', 'Lat Phrao 20 Allay', 32, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.33.1', 6, 'ซอยลาดพร้าว 14', 'Lat Phrao 14 Allay', 33, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.34.1', 6, 'ตรงข้ามบิ๊กซีเอ็กซ์ตร้า ลาดพร้าว', 'Opposite Big C Extra Lat Phrao', 34, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.35.1', 6, 'ไปรษณีย์สามแยกลาดพร้าว', 'Sam Yaek Lat Phrao Post Office', 35, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.36.1', 6, 'ซอยลาดพร้าว 8', 'Lat Phrao 8 Allay', 36, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.37.1', 6, 'ตรงข้ามยูเนี่ยนมอลล์', 'Opposite Union Mall', 37, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.38.1', 6, 'MRT พหลโยธิน (ทางออก 2)', 'MRT Phahon Yothin Station (Exit 2)', 38, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.39.1', 6, 'ธนาคารทหารไทยธนชาต สำนักงานใหญ่', 'TTB Headquarter', 39, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.40.1', 6, 'ตรงข้ามสวนจตุจักร (จุดที่ 2)', 'Opposite Chatuchak Park (Stop 2)', 40, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.41.1', 6, 'กรมการขนส่งทางบก', 'Department Of Land Transport', 41, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.42.1', 6, 'แยกกำแพงเพชร', 'Kamphaeng Phet Junction', 42, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.43.1', 6, 'ตรงข้ามวัดไผ่ตัน', 'Opposite Phai Tan Temple', 43, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.44.1', 6, 'BTS สะพานควาย (ทางออก2)', 'BTS Saphan Khwai (Exit 2)', 44, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.45.1', 6, 'สถานีตำรวจบางซื่อ', 'Police Station Bangsue', 45, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.46.1', 6, 'ซอยสายลม', 'Sai Lom', 46, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.47.1', 6, 'ลา วิลล่า อารีย์', 'La Villa Ari', 47, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.48.1', 6, 'ตรงข้ามซอยราชครู', 'Opposite Ratchakru Allay', 48, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.49.1', 6, 'ซอยพหลโยธิน 2', 'Phahonyothin 2 Allay', 49, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.50.1', 6, 'BTS สนามเป้า (ทางออก4)', 'BTS Sanampao (Exit 4)', 50, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.51.1', 6, 'สถานีวิทยุโทรทัศน์กองทัพบก ช่อง 5', 'Royal Thai Army Radio And Television Channel 5', 51, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.52.1', 6, 'ตรงข้ามซอยลือชา', 'Opposite Luecha Allay', 52, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.53.1', 6, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะราชวิถี)', 'Victory Monument (Ratchawithi)', 53, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.54.1', 6, 'โรงพยาบาลเด็ก', 'Children Hospital', 54, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.55.1', 6, 'โรงเรียนสอนคนตาบอดกรุงเทพ', 'The Bangkok School For the Blind', 55, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.56.1', 6, 'องค์การเภสัชกรรม', 'Government Pharmaceutical Organization', 56, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.57.1', 6, 'กระทรวงอุตสาหกรรม', 'Ministry Of Industry', 57, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.58.1', 6, 'กรมทางหลวง', 'Department Of Highway', 58, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.59.1', 6, 'หลังแยกเสาวนี', 'After Saowani Intersection', 59, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.60.1', 6, 'ก่อนแยกยมราช', 'Before Yommarat Intersection', 60, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.61.1', 6, 'บ้านมนังคศิลา', 'Baan Manangkasila', 61, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.62.1', 6, 'หลังแยกสะพานขาว', 'After Saphan Khao Intersection', 62, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.63.1', 6, 'ตรงข้ามวัดสุนทรธรรมทาน', 'Opposite Sunthon Thammathan Temple', 63, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.64.1', 6, 'ตรงข้ามวัดสระเกศ (ภูเขาทอง)', 'Opposite Saket Temple (Phu Khao Thong)', 64, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.65.1', 6, 'วรจักร', 'Worachak', 65, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.66.1', 6, 'วัดตึก', 'Chaichana Songkhram Temple (Wat Tuek)', 66, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.67.1', 6, 'สำเพ็ง (ฝั่งจักรวรรดิ)', 'Sampeng (Chakrawat Side)', 67, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.68.1', 6, 'ท่ารถสะพานพุทธ', 'Saphan Phut Bus Station', 68, 'Inbound', 'Yes');

INSERT INTO station_stop VALUES ('2-38.1.2', 6, 'ท่ารถสะพานพุทธ', 'Saphan Phut Bus Station', 1, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.2', 6, 'ปากคลองตลาด', 'Pak Khlong Market', 2, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.3.2', 6, 'คลองคูเมืองเดิม (ฝั่งอัษฎางค์)', 'Khlong Khu Mueang Doem (Atsadang Side)', 3, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.4.2', 6, 'MRT สามยอด', 'MRT Sam Yot Station', 4, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.5.2', 6, 'แยกเอสเอบี', 'S.A.B. Intersection', 5, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.6.2', 6, 'ตรงข้ามคลองถม (ฝั่งวรจักร)', 'Opposite Khlong Thom (Worachak Side)', 6, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.7.2', 6, 'ตลาดวรจักร', 'Worachak Market', 7, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.8.2', 6, 'ก่อนแยกแม้นศรี', 'Before Maen Si Intersection', 8, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.9.2', 6, 'วัดสระเกศ (ภูเขาทอง)', 'Saket Temple (Golden Mountain)', 9, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.10.2', 6, 'วัดสุนทรธรรมทาน', 'Sunthon Thammathan Temple', 10, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.11.2', 6, 'ก่อนแยกสะพานขาว', 'Before Saphan Khao Intersection', 11, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.12.2', 6, 'โรงพยาบาลมิชชั่น (ฝั่งหลานหลวง)', 'Mission Hospital (Lan Luang Side)', 12, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.13.2', 6, 'หลังแยกยมราช', 'After Yommarat Intersection', 13, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.14.2', 6, 'ก่อนแยกเสาวนี', 'Before Saowani Intersection', 14, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.15.2', 6, 'กระทรวงการต่างประเทศ', 'Ministry Of Foreign Affairs', 15, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.16.2', 6, 'มหาวิทยาลัยมหิดล (คณะวิทยาศาสตร์)', 'Mahidol University (Faculty Of Science)', 16, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.17.2', 6, 'โรงพยาบาลรามาธิบดี', 'Ramathibodi Hospital', 17, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.18.2', 6, 'วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า', 'Phramongkutklao College Of Medicine', 18, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.19.2', 6, 'โรงพยาบาลพระมงกุฎเกล้า', 'Phramongkutklao Hospital', 19, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.20.2', 6, 'ตรงข้ามโรงพยาบาลเด็ก', 'Opposite Children Hospital', 20, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.21.2', 6, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะพหลโยธิน)', 'Victory Monument (Phahon Yothin)', 21, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.22.2', 6, 'ซอยลือชา', 'Lue Cha Allay', 22, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.23.2', 6, 'โรงพยาบาลพญาไท 2', 'Phyathai 2 Hospital', 23, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.24.2', 6, 'BTS สนามเป้า (ทางออก1)', 'BTS Sanampao (Exit 1)', 24, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.25.2', 6, 'BTS สนามเป้า (ทางออก3)', 'BTS Sanampao (Exit 3)', 25, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.26.2', 6, 'ซอยราชครู', 'Ratchakhru Allay', 26, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.27.2', 6, 'ซอยอารีย์', 'Ari Allay', 27, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.28.2', 6, 'กองบัญชาการตำรวจตระเวนชายแดน', 'Border Patrol Police Bureau', 28, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.29.2', 6, 'ตรงข้ามสถานีตำรวจบางซื่อ', 'Opposite Bangsue Police Station', 29, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.30.2', 6, 'BTS สะพานควาย (ทางออก1)', 'BTS Saphan Khwai (Exit 1)', 30, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.31.2', 6, 'วัดไผ่ตัน', 'Phaiton Temple', 31, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.32.2', 6, 'สวนจตุจักร (จุดที่ 1)', 'Chatuchak Park (Stop 1)', 32, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.33.2', 6, 'ตรงข้ามธนาคารทหารไทยธนชาต สำนักงานใหญ่', 'Opposite TTB Headquarter', 33, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.34.2', 6, 'MRT พหลโยธิน (ทางออก3)', 'MRT Phahonyothin (Exit 3)', 34, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.35.2', 6, 'ยูเนี่ยนมอลล์', 'Union Mall', 35, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.36.2', 6, 'บ้านพร้อมพรรณ', 'Baan Promphan', 36, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.37.2', 6, 'บิ๊กซีเอ็กซ์ตร้า ลาดพร้าว', 'Big C Extra Lat Phrao', 37, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.38.2', 6, 'ซอยลาดพร้าว 15', 'Lat Phrao 15 Allay', 38, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.39.2', 6, 'MRT ลาดพร้าว (ทางออก 3)', 'MRT Lat Phrao Station (Exit 3)', 39, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.40.2', 6, 'ซอยลาดพร้าว 25', 'Lat Phrao 25 Allay', 40, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.41.2', 6, 'สถานีดับเพลิงลาดพร้าว', 'Lat Phrao Fire Station', 41, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.42.2', 6, 'ซอยลาดพร้าว 35/1', 'Lat Phrao 35/1 Allay', 42, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.43.2', 6, 'ซอยภาวนา', 'Phawana Allay', 43, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.44.2', 6, 'ตรงข้ามโรงเรียนพิบูลอุปถัมภ์', 'Opposite Phibool Uppatham School', 44, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.45.2', 6, 'ตลาดสะพาน 2', 'Saphan 2 Market', 45, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.46.2', 6, 'สถานีตำรวจโชคชัย', 'Police Station Chokchai', 46, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.47.2', 6, 'ตลาดโชคชัย 4', 'Chok Chai 4 Market', 47, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.48.2', 6, 'ซอยลาดพร้าว 57', 'Lat Phrao 57 Allay', 48, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.49.2', 6, 'ศึกษาภัณฑ์ลาดพร้าว', 'Suksapan Panit Lat Phrao', 49, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.50.2', 6, 'ไปรษณีย์ลาดพร้าว', 'Post Office Lat Phrao', 50, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.51.2', 6, 'ซอยลาดพร้าว 67/1', 'Lat Phrao 67/1 Allay', 51, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.52.2', 6, 'ซอยลาดพร้าว 71', 'Lat Prao 71 Allay', 52, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.53.2', 6, 'ซอยลาดพร้าว 79', 'Lat Phrao 79 Allay', 53, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.54.2', 6, 'บิ๊กซีลาดพร้าว', 'Big C Lat Phrao', 54, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.55.2', 6, 'ตรงข้ามซอยลาดพร้าว 106', 'Opposite Lat Phrao 106 Allay', 55, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.56.2', 6, 'ซอยลาดพร้าว 89', 'Lat Phrao 89 Allay', 56, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.57.2', 6, 'ซอยลาดพร้าว 93', 'Lat Phrao 93 Allay', 57, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.58.2', 6, 'โรงพยาบาลลาดพร้าว', 'Lat Phrao Hospital', 58, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.59.2', 6, 'ซอยลาดพร้าว 97', 'Lat Phrao 97 Allay', 59, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.60.2', 6, 'ซอยลาดพร้าว 99', 'Lat Phrao 99 Allay', 60, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.61.2', 6, 'ซอยลาดพร้าว 101', 'Lat Phrao 101 Allay', 61, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.62.2', 6, 'ซอยลาดพร้าว 101/2', 'Lat Phrao 101/2 Allay', 62, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.63.2', 6, 'ซอยลาดพร้าว 107', 'Lat Phrao 107 Allay', 63, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.64.2', 6, 'โรงพยาบาลเวชธานี', 'Wetthani Hospital', 64, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.65.2', 6, 'ซอยลาดพร้าว 113', 'Lat Phrao 113 Allay', 65, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.66.2', 6, 'ตรงข้ามแม็คโครลาดพร้าว', 'Opposite Makro Lat Phrao', 66, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.67.2', 6, 'หลังแยกแฮปปี้แลนด์', 'After Happyland Intersection', 67, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.68.2', 6, 'ตรงข้ามตลาดแฮปปี้แลนด์ (ฝั่งสาย 1)', 'Opposite Happyland Market (Sai 1 Side)', 68, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.69.2', 6, 'ลุมพินีเซ็นเตอร์แฮปปี้แลนด์ (อาคาร D)', 'Lumpini Center Happyland (Building D)', 69, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.70.2', 6, 'หมู่บ้านแฮปปี้แลนด์', 'Happyland Village', 70, 'Outbound', 'Yes');

-- ==========================
-- 13 line
-- ==========================
INSERT INTO Station_stop VALUES ('13.1.1', 7, 'อู่คลองเตย', 'Klongtoey Bus Depot', 1, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.1', 7, 'ตรงข้ามเขตการเดินรถที่4', 'Bus Zone 4', 2, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.3.1', 7, 'โรงเรียนคอนแวนต์, ตลาดปีนัง', 'Talat Pinang', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.4.1', 7, 'การไฟฟ้าคลองเตย', 'Electricity Toei', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.5.1', 7, 'ลุมพินีทาวเวอร์ (ตรงข้ามบ่อนกาย)', 'Lumpini Tower (Opposite Brun Kai)', 5, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.6.1', 7, 'สวนลุมพินีป้ายแรก (เข้าเมือง)', 'First stop at Lumphini Park (Entering the city)', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.7.1', 7, 'ตรงข้ามซอยพระเจน', 'Opposite Phra Chen Allay', 7, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.8.1', 7, 'ตรงข้ามสถานีตำรวจลุมพินี', 'Opposite Lumpini Police Station', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.9.1', 7, 'อาคารสินธร, ตรงข้ามสถานฑูตอเมริกา', 'Sindhorn Building, opposite the American Embassy', 9, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.10.1', 7, 'แยกเพลนิจิต, โรงแรมเซ็นเตอร์พ้อยท์', 'Ploenchit Intersection, Center Point Hotel', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.11.1', 7, 'ซอยต้นสน, ตรงข้ามสถานฑูตอังกฤษ', 'Tonson Allay', 11, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.12.1', 7, 'เซ็นทรัลเวิลด์', 'Central World', 12, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.13.1', 7, 'อินทราสแควร์ประตูน้ำ', 'Indra Square Pratunam', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.14.1', 7, 'ซอยรางน้ำ', 'Rang Nam Allay', 14, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.15.1', 7, 'ตรงข้ามวัดตะพาน', 'Opposite Taphan Temple', 15, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.16.1', 7, 'สำนักงาน ป.ป.ส.', 'ONCB Office', 16, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.17.1', 7, 'รร.พิบูลประชาสรรค์', 'Piboon Prachasan School', 17, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.18.1', 7, 'สถาบันราชานุกูล', 'Rajanukul Institute', 18, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.19.1', 7, 'แยกประชาสงเคราะห์', 'Pracha Songkhro Intersection', 19, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.20.1', 7, 'ประชาสงเคราะห์1', 'Pracha Songkhro 1', 20, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.21.1', 7, 'สำนักงานเคหะดินแดง', 'Dindaeng Housing Office', 21, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.22.1', 7, 'ตลาดดินแดง', 'Dindaeng Market', 22, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.23.1', 7, 'โรงเรียนวชิรศิษฐ์', 'Wichutit School', 23, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.24.1', 7, 'ศูนย์บริการสาธารณสุข 4', 'Health Center 4', 24, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.25.1', 7, 'ตรงข้ามโรงเรียนพร้มพรรณวิทยา', 'Opposite Promphanwittaya School', 25, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.26.1', 7, 'ซอยประชาสงเคราะห์21', 'Pracha Songkhro 21', 26, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.27.1', 7, 'ซอยประชาสงเคราะห์23', 'Pracha Songkhro 23', 27, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.28.1', 7, 'วัดพรหมวงศาราม', 'Phrom Wong Saram Temple', 28, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.29.1', 7, 'TVC คอนโดมิเนียม', 'TVC Condominium', 29, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.30.1', 7, 'ตรงข้ามโรงเรียนอำนวย', 'Opposite Amnuayvid School', 30, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.31.1', 7, 'ท่ารถห้วยขวาง', 'Huai Khwang port', 31, 'Inbound', 'Yes');

INSERT INTO Station_stop VALUES ('13.1.2', 7, 'ท่ารถห้วยขวาง', 'Huai Khwang port', 1, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.2', 7, 'สถานีดับเพลิงห้วยขวาง, สาธารณสุข52', 'Huai Khwang Fire Station, Public Health 52', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.3.2', 7, 'ตลาดห้วยขวางหลังโรงเรียนสามเสนนอก', 'Huai Khwang Market behind Samsen Nok School', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.4.2', 7, 'ธนาคารกรุงไทยสาขาห้วยขวาง', 'Krungthai Bank Huai Khwang Branch', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.5.2', 7, 'ตรงข้ามทีวีซีคอนโดมิเนียม', 'Opposite TVC Condominium', 5, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.6.2', 7, 'ตรงข้ามวัดพรหมวงศาราม', 'Opposite Phrom Wong Saram Temple', 6, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.7.2', 7, 'ดีดีทาวเวอร์', 'Dd Tower', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.8.2', 7, 'ซอยประชาสงเคราะห์16-18', 'Pracha Songkhro 16-18', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.9.2', 7, 'โรงเรียนพร้มพรรณวิทยา', 'Promphanwittaya School', 9, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.10.2', 7, 'ตรงข้ามศูนย์บริการสาธารณสุข 4', 'Opposite Health Center 4', 10, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.11.2', 7, 'ตรงข้ามโรงเรียนวชิรศิษฐ์', 'Opposite Wichutit School', 11, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.12.2', 7, 'ตรงข้ามตลาดดินแดง', 'Opposite Dindaeng Market', 12, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.13.2', 7, 'ตรงข้ามสำนักงานเคหะดินแดง', 'Opposite the Din Daeng Housing Office', 13, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.14.2', 7, 'ประชาสงเคราะห์2', 'Pracha Songkhro 2', 14, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.15.2', 7, 'แฟลตดินแดง (ป้าย1)', 'Dindaeng Housing (Stop.1)', 15, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.16.2', 7, 'แฟลตดินแดง (ป้าย2)', 'Dindaeng Housing (Stop.2)', 16, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.17.2', 7, 'ตรงข้ามโรงเรียนพิบูลประชาสรรค์', 'Opposite Piboon Prachasan School', 17, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.18.2', 7, 'ตลาดศรีวานิช', 'Sriwanit Market', 18, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.19.2', 7, 'ตรงข้ามซอยรางน้ำ', 'Opposite Rang Nam Allay', 19, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.20.2', 7, 'ตรงข้ามอินทราสแควร์ประตูน้ำ', 'Opposite Indra Square Pratunam', 20, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.21.2', 7, 'บิ๊กซีราชดำริ', 'Big C Rajdamri', 21, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.22.2', 7, 'เพนนินซูลาพลาซ่า', 'Peninsula Plaza', 22, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.23.2', 7, 'BTS ราชดำริ (ทางออก2)', 'BTS Ratchadamri (Exit 2)', 23, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.24.2', 7, 'สถาบันสอนภาษา', 'AUA Language Institute', 24, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.25.2', 7, 'หลังสวน1 อาคารปาร์คเพลส', 'Lang Suan 1, Park Place', 25, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.26.2', 7, 'หลังสวน2', 'Lang Suan 2', 26, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.27.2', 7, 'สมาคมสร้างคุณค่าในประเทศไทย', 'Association of Value Creation in Thailand', 27, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.28.2', 7, 'ซอยพระเจน', 'Phra Chen Allay', 28, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.29.2', 7, 'สวนลุมไนท์บาซาร์', 'Suan Lum Night Bazaar', 29, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.30.2', 7, 'บ่อนกาย', 'Brun Kai', 30, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.31.2', 7, 'ตลาดคลองเตย (ถนนสุนทรโกษา ขาออก)', 'Talat Khlong Toei', 31, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.32.2', 7, 'ตรงข้ามสโมสรการท่าเรือ', 'Opposite Port F.C.', 32, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.33.2', 7, 'ตรงข้ามสนามกีฬาการท่าเรือ', 'Opposite Sanamkila Kan Tharuea', 33, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.34.2', 7, 'ซอยคั่วพริก ก่อนถึงแยกกรมศุลกากร', 'Kua Phrik Allay, before Customs Department Intersection', 34, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.35.2', 7, 'อู่คลองเตย', 'Klongtoey Bus Depot', 35, 'Outbound', 'No');

-- ==========================
-- 2-53 line 
-- ==========================
INSERT INTO station_stop VALUES ('2-53.1.1', 8, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะดินแดง)', 'Victory Monument (Din Daeng)', 1, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.2.1', 8, 'ซอยลือชา', 'Lue Cha Allay', 2, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.3.1', 8, 'โรงพยาบาลพญาไท 2', 'Phyathai 2 Hospital', 3, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.4.1', 8, 'BTS สนามเป้า (ทางออก 1)', 'BTS Sanampao (Exit 1)', 4, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.5.1', 8, 'BTS สนามเป้า (ทางออก 3)', 'BTS Sanampao (Exit 3)', 5, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.6.1', 8, 'ซอยราชครู', 'Ratchakhru Allay', 6, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.7.1', 8, 'ซอยอารีย์', 'Ari Allay', 7, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.8.1', 8, 'กองบัญชาการตำรวจตระเวนชายแดน', 'Border Patrol Police Bureau', 8, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.9.1', 8, 'ตรงข้าม สถานีตำรวจบางซื่อ', 'Opposite Bangsue Police Station', 9, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.10.1', 8, 'BTS สะพานควาย (ทางออก 1)', 'BTS Saphan Khwai (Exit 1)', 10, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.11.1', 8, 'วัดไผ่ตัน', 'Phaiton Temple', 11, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.12.1', 8, 'สวนจตุจักร (จุดที่1)', 'Chatuchak Park (Stop 1)', 12, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.13.1', 8, 'สวนจตุจักร (จุดที่2)', 'Chatuchak Park (Stop 2)', 13, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.14.1', 8, 'ตรงข้ามธนาคารทหารไทยธนชาต สำนักงานใหญ่', 'Opposite TTB Headquarter', 14, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.15.1', 8, 'สวนรถไฟ', 'Rot Fai Park', 15, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.16.1', 8, 'สำนักงานใหญ่ ปตท.', 'PTT Headquarter', 16, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.17.1', 8, 'ซอยวิภาวดีรังสิต 13', 'Vibhavadi Rangsit 13 Allay', 17, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.18.1', 8, 'ตรงข้ามตรีเพชรอีซูซุ', 'Opposite Tri Petch Isuzu', 18, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.19.1', 8, 'ตรงข้าม SCB Park Plaza', 'Opposite SCB Park Plaza', 19, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.20.1', 8, 'แยกรัชโยธิน', 'Ratchayothin Intersection', 20, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.21.1', 8, 'ซอยรัชดาภิเษก 42', 'Ratchadaphisek 42 Allay', 21, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.22.1', 8, 'ซอยเสือใหญ่', 'Suea Yai Allay', 22, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.23.1', 8, 'มหาวิทยาลัยราชภัฏจันทรเกษม', 'Chandrakasem Rajabhat University', 23, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.24.1', 8, 'สำนักงาน คปภ.', 'Office Of Insurance Commission', 24, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.25.1', 8, 'กรมส่งเสริมการค้าระหว่างประเทศ', 'Department Of International Trade Promotion', 25, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.26.1', 8, 'อาคารโอลิมเปีย', 'Olympia Thai Tower', 26, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.27.1', 8, 'ตรงข้ามโรงเรียนปัญจทรัพย์', 'Opposite Panchasap School', 27, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.28.1', 8, 'บุญถาวร รัชดาภิเษก (ขาเข้า)', 'Boonthavorn Ratchadaphisek (Inbound)', 28, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.29.1', 8, 'ปรีชา คอมเพล็กซ์', 'Preecha Complex', 29, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.30.1', 8, 'อาคารเมืองไทย-ภัทร', 'Muang Thai-Phat Building', 30, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.31.1', 8, 'ตรงข้ามโรงเรียนเตรียมอุดมศึกษาน้อมเกล้า กนุนที', 'Opposite Triam Udom Suksa Nomklao (Kunnatee School)', 31, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.32.1', 8, 'MRT ห้วยขวาง (ทางออก 1)', 'MRT Huai Khwang (Exit 1)', 32, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.33.1', 8, 'โรงแรมสวิสโซเทล กรุงเทพฯ รัชดา', 'Swissotel Bangkok Ratchada', 33, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.34.1', 8, 'โรงเรียนเตรียมอุดมศึกษาพัฒนาการ รัชดา', 'Triam Udom Suksa Pattanakarn Ratchada School', 34, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.35.1', 8, 'ตรงข้ามบิ๊กซีเอ็กซ์ตร้า รัชดาภิเษก', 'Opposite Big C Extra Ratchadaphisek', 35, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.36.1', 8, 'ตรงข้ามเอสพลานาด รัชดาภิเษก', 'Opposite Esplanade Ratchadaphisek', 36, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.37.1', 8, 'ตรงข้ามสถานทูตจีน', 'Opposite Embassy of China', 37, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.38.1', 8, 'ตรงข้ามตลาดอยู่เจริญ', 'Opposite Yoo Charoen Market', 38, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.39.1', 8, 'ตรงข้ามตลาดขวัญพัฒนา', 'Opposite Khwan Phatthana Market', 39, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.40.1', 8, 'โบสถ์แม่พระฟาติมา', 'Fatima Catholic Church', 40, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.41.1', 8, 'แฟลตดินแดง (อาคาร 7)', 'Din Daeng Flat (Building 7)', 41, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.42.1', 8, 'แฟลตดินแดง (อาคาร 5)', 'Din Daeng Flat (Building 5)', 42, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.43.1', 8, 'ตรงข้ามโรงเรียนพิบูลประชาสรรค์', 'Opposite Piboon Prachasan School', 43, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.44.1', 8, 'ตรงข้ามสำนักงาน ป.ป.ส.', 'Opposite Office Of the Narcotics Control Board', 44, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.45.1', 8, 'สวนสันติภาพ', 'Santiphap Park', 45, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.46.1', 8, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะดินแดง)', 'Victory Monument (Din Daeng)', 46, 'Clockwise', 'Yes');

INSERT INTO station_stop VALUES ('2-53.1.2', 8, 'อนุสาวรีย์ชัยฯ (พหลโยธิน) (ขาเข้า)', 'Victory Monument (Phahonyothin In)', 1, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.2.2', 8, 'ตรงข้ามสวนสาธารณะ', 'Opposite Sanampao Park', 2, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.3.2', 8, 'สำนักงาน ป.ป.ส.', 'Office of the Narcotics Control Board', 3, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.4.2', 8, 'โรงเรียนบุญถาวรพหลโยธิน', 'Boonthavorn School', 4, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.5.2', 8, 'สถาบันราชภัฏ', 'Rajabhat Institute', 5, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.6.2', 8, 'ตรงข้ามโบสถ์แม่พระฟาติมา', 'Opposite Fatima Catholic Church', 6, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.7.2', 8, 'ตลาดอยู่เจริญ', 'Yu Charoen Market', 7, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.8.2', 8, 'ฟิวเจอร์ทาวน์', 'Future Town', 8, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.9.2', 8, 'สถานทูตจีน', 'Embassy of China', 9, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.10.2', 8, 'เอสพลานาด รัชดาภิเษก', 'Esplanade Ratchadapisek', 10, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.11.2', 8, 'บิ๊กซีเอ็กซ์ตร้า รัชดาภิเษก', 'Big C Extra Ratchadapisek', 11, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.12.2', 8, 'โรงเรียนเตรียมอุดมศึกษาพัฒนาการ รัชดา', 'Triam Udom Suksa Pattanakarn Ratchada School', 12, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.13.2', 8, 'โรงแรมดิ เอมเมอรัลด์', 'The Emerald Hotel', 13, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.14.2', 8, 'MRT ห้วยขวาง (ทางออก 3)', 'MRT Huai Khwang (Exit 3)', 14, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.15.2', 8, 'MRT ห้วยขวาง (ทางออก 4)', 'MRT Huai Khwang (Exit 4)', 15, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.16.2', 8, 'โรงเรียนเตรียมอุดมศึกษาน้อมเกล้า กนุนที', 'Triam Udom Suksa Nomklao Kunnatee School', 16, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.17.2', 8, 'อาคารโอลิมเปีย', 'Olympia Thai Tower', 17, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.18.2', 8, 'สถานีตำรวจพหลโยธิน', 'Police Office Sutthisan', 18, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.19.2', 8, 'บุญถาวร รัชดาภิเษก (ขาออก)', 'Boonthavorn Ratchadaphisek (Outbound)', 19, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.20.2', 8, 'โรงเรียนอนุบาลโชคชัย', 'Chokchai School', 20, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.21.2', 8, 'ศาลาว่าการกรุงเทพฯ เขตดินแดง', 'Bangkok North Municipal Court', 21, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.22.2', 8, 'ศาลอาญา', 'Criminal Court', 22, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.23.2', 8, 'ตรงข้ามมหาวิทยาลัยราชภัฏจันทรเกษม', 'Opposite Chandrakasem Rajabhat University', 23, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.24.2', 8, 'ตรงข้ามโรงเรียนสุวรรณศึกษา', 'Opposite Suan Yai', 24, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.25.2', 8, 'ตรงข้ามซอยรัชดาภิเษก 42', 'Opposite Ratchadaphisek 42 Allay', 25, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.26.2', 8, 'แยกรัชโยธิน', 'Police Station (Phahonyothin)', 26, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.27.2', 8, 'เอสซีบี ปาร์ค', 'SCB Park Plaza', 27, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.28.2', 8, 'โรงเรียนปัญจทรัพย์', 'Panchasap School', 28, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.29.2', 8, 'กรมการขนส่งทางบก', 'Department of Land Transport', 29, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.30.2', 8, 'แยกกำแพงเพชร', 'Kamphaeng Phet Junction', 30, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.31.2', 8, 'ตรงข้ามกรมวิทย์', 'Opposite VAT Phah Tlan', 31, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.32.2', 8, 'BTS สะพานควาย (ทางออก 2)', 'BTS Saphan Khwai (Exit 2)', 32, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.33.2', 8, 'สถานีตำรวจบางซื่อ', 'Police Station Bangsue', 33, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.34.2', 8, 'ซอยราชครู', 'Rachakru Allay', 34, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.35.2', 8, 'ซอยอารีย์', 'Ari Allay', 35, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.36.2', 8, 'อนุสาวรีย์ชัยฯ (ราชวิถี) (ขาเข้า)', 'Victory Monument (Din Daeng In)', 36, 'Counterclockwise', 'Yes');

-- ==========================
-- 12 line 
-- ==========================
INSERT INTO Station_stop VALUES ('12.1.1', 9, 'สถานีดับเพลิงห้วยขวาง, สาธารณสุข 52', 'Huai Khwang Fire Station, Public Health 52', 1, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.1', 9, 'โรงเรียนสามเสนนอก', 'Samsen Nok School', 2, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.3.1', 9, 'ธนาคารกรุงไทย สาขาห้วยขวาง', 'Krung Thai Bank (Huai Khwang)', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.4.1', 9, 'หอนาฬิกาห้วยขวาง', 'Huai Khwang Clock Tower', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.5.1', 9, 'ตรงข้ามทีวีซี คอนโดมิเนียม', 'Opposite TVC Condominium', 5, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.6.1', 9, 'ตรงข้ามวัดพรหมวงศาราม', 'Opposite Phrom Wong Saram Temple', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.7.1', 9, 'ดีดี ทาวเวอร์', 'DD Tower', 7, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.8.1', 9, 'ซอยประชาสงเคราะห์ 16-18', 'Pracha Songkhro 16-18 Allay', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.9.1', 9, 'โรงเรียนพร้อมพรรณวิทยา', 'Promphanwittaya School', 9, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.10.1', 9, 'ตรงข้ามศูนย์บริการสาธารณสุข 4', 'Opposite Health Center 4', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.11.1', 9, 'ตรงข้ามโรงเรียนวิชูทิตย์', 'Opposite Wichutit School', 11, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.12.1', 9, 'ตรงข้ามตลาดดินแดง', 'Opposite Dindaeng Market', 12, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.13.1', 9, 'ตรงข้ามสำนักงานเคหะดินแดง', 'Opposite Dindaeng Housing Office', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.14.1', 9, 'ประชาสงเคราะห์ 2', 'Pracha Songkhro 2', 14, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.15.1', 9, 'แฟลตดินแดง (ป้าย 1)', 'Dindaeng Housing Stop 1', 15, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.16.1', 9, 'แฟลตดินแดง (ป้าย 2)', 'Dindaeng Housing Stop 2', 16, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.17.1', 9, 'ตรงข้ามโรงเรียนพิบูลประชาสรรค์', 'Opposite Piboon Prachasan School', 17, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.18.1', 9, 'ตลาดศรีวานิช', 'Sriwanit Market', 18, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.19.1', 9, 'สวนสันติภาพ', 'Santiphap Park', 19, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.20.1', 9, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะราชวิถี)', 'Victory Monument (Ratchawithi)', 20, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.21.1', 9, 'โรงพยาบาลเด็ก', 'Children’s Hospital', 21, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.22.1', 9, 'โรงเรียนสอนคนตาบอดกรุงเทพ', 'Bangkok School for the Blind', 22, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.23.1', 9, 'บ้านราชวิถี (ฝั่งพระราม 6)', 'Ban Ratchawithi (Rama VI side)', 23, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.24.1', 9, 'สำนักงานประปา สาขาแม้นศรี', 'Maensir Waterworks Office', 24, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.25.1', 9, 'ซอยสุโขทัย 1, 3', 'Sukho Thai 1, 3 Allay', 25, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.26.1', 9, 'ซอยสุโขทัย 5', 'Sukho Thai 5 Allay', 26, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.27.1', 9, 'ตรงข้ามโรงเรียนสุโขทัย', 'Opposite Sukhothai School', 27, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.28.1', 9, 'ตรงข้ามสำนักงานเขตดุสิต', 'Opposite Dusit District Office', 28, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.29.1', 9, 'ตรงข้ามสภาสตรีแห่งประเทศไทย', 'Opposite Women’s Council of Thailand', 29, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.30.1', 9, 'ตรงข้ามโรงเรียนพันธะวัฒนา', 'Opposite Pantawattana School', 30, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.31.1', 9, 'ร้านศิลปาชีพ 905', 'Silapacheep Shop 905', 31, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.32.1', 9, 'สวนรื่นฤดี, ตรงข้ามกองอำนวยการรักษาความมั่นคงในราชอาณาจักร', 'Suan Ruen-Rudi, Opposite Internal Security Command', 32, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.33.1', 9, 'มหาวิทยาลัยราชภัฏสวนดุสิต (แยกการเรือน)', 'Suan Dusit Rajabhat University (Home Economics Intersection)', 33, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.34.1', 9, 'ตรงข้ามกรมป้องกันและบรรเทาสาธารณภัย', 'Opposite Department of Disaster Prevention and Mitigation', 34, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.35.1', 9, 'พระตำหนักวังสวนกุหลาบ', 'Vimanmek Mansion', 35, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.36.1', 9, 'ครุสภา', 'Teachers Council of Thailand', 36, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.37.1', 9, 'วัดมกุฏกษัตริย์', 'Makutkasat Temple', 37, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.38.1', 9, 'กองบัญชาการกองทัพบก', 'Royal Thai Army', 38, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.39.1', 9, 'โรงแรม เดอ ม็อค (ตรงข้ามวัดตรีทศเทพ)', 'Hotel De Moc (Opposite Tri Thotsathep Temple)', 39, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.40.1', 9, 'สะพานวันชาติ', 'Wan Chat Bridge', 40, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.41.1', 9, 'ศาลาว่าการกรุงเทพมหานคร', 'Bangkok City Hall', 41, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.42.1', 9, 'เสาชิงชา', 'Sao Chingcha', 42, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.43.1', 9, 'วัดสุทัศน์', 'Suthat Temple', 43, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.44.1', 9, 'ก่อนสี่กั๊กพระยาศรี', 'Before Si Kak Phraya Sri', 44, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.45.1', 9, 'หน่วยบัญชาการรักษาดินแดน', 'Territorial Defense Command', 45, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.46.1', 9, 'สวนเจ้าเชตุ', 'Chao Chet Park', 46, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.47.1', 9, 'โรงเรียนวัดราชบพิธ (ท่าปลายทาง ปากคลองตลาด)', 'Wat Rajabophit School (Terminus Pak Khlong Market)', 47, 'Inbound', 'Yes');

INSERT INTO Station_stop VALUES ('12.1.2', 9, 'โรงเรียนวัดราชบพิธ (ท่าปลายทาง ปากคลองตลาด)', 'Wat Rajabophit School (Terminus Pak Khlong Market)', 1, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.2', 9, 'พระพพิธิ (ตรงข้าม กรมที่ดิน)', 'Phra Phiphit (Opposite Department of Lands)', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.3.2', 9, 'บ้านหม้อ', 'Ban Mo', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.4.2', 9, 'ตรงข้ามวัดสุทัศน์, ร้านวิจิตรพาณิชย์', 'Opposite Suthat Temple, Vijit Panich Shop', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.5.2', 9, 'ตรงข้ามศาลาว่าการกรุงเทพมหานคร', 'Opposite Bangkok City Hall', 5, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.6.2', 9, 'โรงเรียนสตรีวิทยา', 'Satriwittaya School', 6, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.7.2', 9, 'วัดตรีทศเทพ', 'Tri Thotsathep Temple', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.8.2', 9, 'ตรงข้ามกองบัญชาการกองทัพบก', 'Opposite Royal Thai Army', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.9.2', 9, 'ตรงข้ามวัดมกุฏกษัตริย์', 'Opposite Makutkasat Temple', 9, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.10.2', 9, 'สำนักงานทรัพย์สินส่วนพระมหากษัตริย์ (ตรงข้าม ครุสภา)', 'Crown Property Bureau Office (Opposite Teachers Council)', 10, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.11.2', 9, 'โรงเรียนราชวินิต', 'Rajavinit School', 11, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.12.2', 9, 'กรมป้องกันและบรรเทาสาธารณภัย กระทรวงมหาดไทย', 'Department of Disaster Prevention and Mitigation, Ministry of Interior', 12, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.13.2', 9, 'มหาวิทยาลัยราชภัฏสวนดุสิต', 'Suan Dusit Rajabhat University', 13, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.14.2', 9, 'ซอยสวนอ้อย, กองอำนวยการรักษาความมั่นคงภายในราชอาณาจักร', 'Suan Oi Allay, Internal Security Command', 14, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.15.2', 9, 'พณิชยการสุโขทัย', 'Bangkok Health and Services Technological College', 15, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.16.2', 9, 'สภาสตรีแห่งประเทศไทย', 'Women’s Council of Thailand', 16, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.17.2', 9, 'สำนักงานเขตดุสิต', 'Dusit District Office', 17, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.18.2', 9, 'พรรคชาติพัฒนา (ถนนสุโขทัย)', 'Chart Pattana Party (Sukhothai Rd)', 18, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.19.2', 9, 'ตรงข้ามซอยสุโขทัย 5', 'Opposite Sukho Thai 5 Allay', 19, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.20.2', 9, 'ตรงข้ามซอยสุโขทัย 1', 'Opposite Sukho Thai 1 Allay', 20, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.21.2', 9, 'แยกสวรรคโลก (ขาเข้า)', 'Sawankhalok Intersection (Inbound)', 21, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.22.2', 9, 'บ้านราชวิถี', 'Ban Ratchawithi', 22, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.23.2', 9, 'วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า', 'Phramongkutklao College of Medicine', 23, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.24.2', 9, 'พระราชวังพญาไท', 'Phayathai Palace', 24, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.25.2', 9, 'ตรงข้ามโรงพยาบาลเด็ก', 'Opposite Children’s Hospital', 25, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.26.2', 9, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะดินแดง)', 'Victory Monument (Din Daeng)', 26, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.27.2', 9, 'ตรงข้ามสวนสันติภาพ', 'Opposite Santiphap Park', 27, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.28.2', 9, 'สำนักงาน ป.ป.ส.', 'Oncb Office', 28, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.29.2', 9, 'โรงเรียนพิบูลประชาสรรค์', 'Piboon Prachasan School', 29, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.30.2', 9, 'สถาบันราชานุกูล', 'Rajanukul Institute', 30, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.31.2', 9, 'แยกประชาสงเคราะห์', 'Pracha Songkhro Intersection', 31, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.32.2', 9, 'ประชาสงเคราะห์ 1', 'Pracha Songkhro 1', 32, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.33.2', 9, 'สำนักงานเขตดินแดง', 'Dindaeng Housing Office', 33, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.34.2', 9, 'ตลาดดินแดง', 'Dindaeng Market', 34, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.35.2', 9, 'โรงเรียนวิชูติทย์', 'Wichutit School', 35, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.36.2', 9, 'ศูนย์บริการสาธารณสุข 4', 'Health Center 4', 36, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.37.2', 9, 'ตรงข้ามโรงเรียนพร้อมพรรณวิทยา', 'Opposite Promphanwittaya School', 37, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.38.2', 9, 'ซอยประชาสงเคราะห์ 21', 'Pracha Songkhro 21', 38, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.39.2', 9, 'ซอยประชาสงเคราะห์ 23', 'Pracha Songkhro 23', 39, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.40.2', 9, 'วัดพรหมวงศาราม', 'Phrom Wong Saram Temple', 40, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.41.2', 9, 'ทีวีซีคอนโดมิเนียม', 'TVC Condominium', 41, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.42.2', 9, 'ตรงข้ามโรงเรียนอำนวย', 'Opposite Amnuay School', 42, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.43.2', 9, 'หอนาฬิกาห้วยขวาง, ศูนย์รับเลี้ยงเด็กห้วยขวาง', 'Huai Khwang Clock Tower, Huai Khwang Daycare Center', 43, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.44.2', 9, 'ตรงข้ามตลาดห้วยขวาง', 'Opposite Huay Kwang Market', 44, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.45.2', 9, 'สถานีดับเพลิงห้วยขวาง, สาธารณสุข 52', 'Huai Khwang Fire Station, Public Health 52', 45, 'Outbound', 'Yes');

-- ==========================
-- S5 line
-- ==========================
INSERT INTO Station_stop VALUES ('S5.1.1', 10, 'ก่อนแยกแฮปปี้แลนด์', 'Before Happyland Junction', 1, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.1', 10, 'แยกลําสาลี (ฝั่งศรีนครินทร์ขาออก)', 'Lam Sali Intersection (Srinakarin Side Outbound)', 2, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.3.1', 10, 'ซอยศรีนครินทร์ 1', 'Srinakarin 1 Allay', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.4.1', 10, 'โรงแรมเดอะแกรนด์โฟรว์งส์', 'The Grand Fourwings Hotel', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.5.1', 10, 'ต่างระดับกรุงเทพกรีฑา (ขาออก)', 'Krungthep Kreetha Interchange (Outbound)', 5, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.6.1', 10, 'ซอยศรีนครินทร์ 7', 'Srinakarin 7 Allay', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.7.1', 10, 'ตรงข้ามโรงพยาบาลสมิติเวช ศรีนครินทร์', 'Opposite Samitivej Srinakarin Hospital', 7, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.8.1', 10, 'ARL หัวหมาก', 'ARL Hua Mak Station', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.9.1', 10, 'หลังแยกพัฒนาการ', 'After Phatthanakan Intersection', 9, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.10.1', 10, 'ซอยศรีนครินทร์ 23', 'Srinakarin 23 Allay', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.11.1', 10, 'อาคารโมเดิร์นฟอร์ม', 'Modernform', 11, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.12.1', 10, 'ธัญญาพาร์ค', 'Thanya Park', 12, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.13.1', 10, 'อาคาร 21 ทาวเวอร์', 'Twenty One Tower', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.14.1', 10, 'ตรงข้ามตลาดเอี่ยมสมบัติ', 'Opposite Eiem Sombat Market', 14, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.15.1', 10, 'ตรงข้ามไปรษณีย์ไทย สาขาอ่อนนุช', 'Post Office Onnut', 15, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.16.1', 10, 'ตรงข้ามหมู่บ้านเสรี–อ่อนนุช', 'Opposite Baan Seri – Onnut', 16, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.17.1', 10, 'ต่างระดับอ่อนนุช', 'On Nut Interchange', 17, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.18.1', 10, 'ซอยอ่อนนุช 55', 'On Nut 55 Allay', 18, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.19.1', 10, 'ตรงข้ามรองเท้าเอสซีเอส', 'Opposite Scs Shoes', 19, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.20.1', 10, 'ซอยอ่อนนุช 55/2', 'On Nut 55/2 Allay', 20, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.21.1', 10, 'ตรงข้ามโลตัสอ่อนนุช 80', 'Opposite Lotus On Nut 80', 21, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.22.1', 10, 'สุเหร่าทางควาย', 'Surao Thang Kwai', 22, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.23.1', 10, 'หมู่บ้านชมเดือน 3', 'Chom Duean 3 Village', 23, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.24.1', 10, 'ซอยอ่อนนุช 63', 'On Nut 63 Allay', 24, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.25.1', 10, 'ซอยอ่อนนุช 65', 'On Nut 65 Allay', 25, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.26.1', 10, 'ตรงข้ามซอยอ่อนนุช 84', 'Opposite On Nut 84 Allay', 26, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.27.1', 10, 'วัดกระทุ่มเสือปลา', 'Krathum Suea Pla Temple', 27, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.28.1', 10, 'ซอยอ่อนนุช 67/3', 'On Nut 67/3 Allay', 28, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.29.1', 10, 'หลังแยกอ่อนนุช-สุขาภิบาล 2', 'After Onnut-Sukhapiban 2 Junction', 29, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.30.1', 10, 'ตรงข้ามโรงพยาบาลสิรินธร', 'Opposite Sirindhorn Hospital', 30, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.31.1', 10, 'ตลาดนำ้-ชัย', 'Namchai Market', 31, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.32.1', 10, 'ตรงข้ามโรงเรียนประเวศพิทยาคาร', 'Opposite Prawet Pittayakhan School', 32, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.33.1', 10, 'โรงเรียนพร้อม', 'Prom School', 33, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.34.1', 10, 'วัดลานบุญ', 'Lan Bun Temple', 34, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.35.1', 10, 'ศูนย์บริการสาธารณสุข 46', 'Public Health Service Center 46', 35, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.36.1', 10, 'โฮมโปร ลาดกระบัง', 'Homepro-Lat Krabang', 36, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.37.1', 10, 'แม็คโคร ลาดกระบัง', 'Makro Lat Krabang', 37, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.38.1', 10, 'ซอยลาดกระบัง 1/7', 'Lat Krabang 1/7 Allay', 38, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.39.1', 10, 'ตรงข้ามหมู่บ้านเดอะยูโรเปี้ยน', 'Opposite The European Village', 39, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.40.1', 10, 'ตรงข้ามเขตปลอดอากร สุวรรณภูมิ (ประตู1) (จุดที่1)', 'Opposite Suvarnabhumi Airport Free Zone (Entrance 1) (Stop 1)', 40, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.41.1', 10, 'ครัวการบินไทย สุวรรณภูมิ', 'Suvarnabhumi Thai Catering', 41, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.42.1', 10, 'สถานีดับเพลิงสุวรรณภูมิ', 'Suvarnabhumi Fire Station', 42, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.43.1', 10, 'สนามบินสุวรรณภูมิ (ศูนย์การขนส่งสาธารณะ)', 'Public Transportation Center Of Suvarnabhumi Airport Stop', 43, 'Inbound', 'Yes');

INSERT INTO Station_stop VALUES ('S5.1.2', 10, 'สนามบินสุวรรณภูมิ (ศูนย์การขนส่งสาธารณะ)', 'Public Transportation Center Of Suvarnabhumi Airport Stop', 1, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.2', 10, 'ตรงข้ามอาคารที่พักเวร ฝรภ.สุวรรณภูมิ', 'Opposite Suvarnabhumi Official Residence Of Security Department', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.3.2', 10, 'LSG สกายเชฟส์', 'LSG Sky Chefs', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.4.2', 10, 'ตรงข้ามสถานีดับเพลิงสุวรรณภูมิ', 'Opposite the Fire Station Suvarnabhumi Airport', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.5.2', 10, 'การบินไทยสุวรรณภูมิ (ตึกปฏิบัติการภาคพื้นดิน) (จุดที่3)', 'Suvarnabhumi (TG Ground Operation Control Center)', 5, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.6.2', 10, 'เขตปลอดอากร สุวรรณภูมิ (ประตู1)', 'Suvarnabhumi Airport Free Zone (Entrance 1) (Stop 1)', 6, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.7.2', 10, 'ตรงข้ามวัดสังฆราชา', 'Opposite Sangkha Racha Temple', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.8.2', 10, 'ซอยลาดกระบัง 28', 'Lat Krabang 28 Allay', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.9.2', 10, 'หมู่บ้านเดอะยูโรเปี้ยน', 'The European Village', 9, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.10.2', 10, 'ซอยลาดกระบัง 24', 'Lat Krabang 24 Allay', 10, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.11.2', 10, 'เดอะพาราโซ่ ลาดกระบัง', 'The Paseo Mall, Lat Krabang', 11, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.12.2', 10, 'โรบินสัน ลาดกระบัง', 'Robinson Lifestyle Lat Krabang', 12, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.13.2', 10, 'ตรงข้ามศูนย์บริการสาธารณสุข 46', 'Opposite Public Health Service Center 46', 13, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.14.2', 10, 'ตรงข้ามวัดลานบุญ', 'Opposite Lan Boon Temple', 14, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.15.2', 10, 'หมู่บ้านไทยสมุทร ลาดกระบัง', 'Thai Samut Lat Krabang Village', 15, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.16.2', 10, 'โรงเรียนประเวศพิทยาคาร', 'Prawet Pittayakarn School', 16, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.17.2', 10, 'ตรงข้ามตลาดนำ้-ชัย', 'Opposite Namchai Market', 17, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.18.2', 10, 'โรงพยาบาลสิรินธร', 'Sirindhorn Hospital', 18, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.19.2', 10, 'ก่อนแยกอ่อนนุช-สุขาภิบาล 2', 'Before Onnut-Sukhapiban 2 Junction', 19, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.20.2', 10, 'ซอยอ่อนนุช 88', 'On Nut 88 Allay', 20, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.21.2', 10, 'โรงงานขยะมูลฝอยอ่อนนุช', 'On Nut Incineration Plant', 21, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.22.2', 10, 'ซอยอ่อนนุช 84', 'On Nut 84 Allay', 22, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.23.2', 10, 'ซอยอ่อนนุช 82', 'On Nut 82 Allay', 23, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.24.2', 10, 'ตรงข้ามหมู่บ้านชมเดือน 3', 'Opposite Chom Duean 3 Village', 24, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.25.2', 10, 'ตรงข้ามสุเหร่าทางควาย', 'Opposite Surao Thang Kwai', 25, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.26.2', 10, 'เทสโก้โลตัสอ่อนนุช 80', 'Tesco Lotus On Nut 80', 26, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.27.2', 10, 'ซอยอ่อนนุช 78', 'On Nut 78 Allay', 27, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.28.2', 10, 'รองเท้าเอสซีเอส', 'Scs Shoes', 28, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.29.2', 10, 'ซอยอ่อนนุช 74/3', 'Seri-Onnut Village', 29, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.30.2', 10, 'หมู่บ้านเสรี-อ่อนนุช', 'Seri-Onnut Village', 30, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.31.2', 10, 'ไปรษณีย์อ่อนนุช', 'Post Office Onnut', 31, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.32.2', 10, 'ตลาดเอี่ยมสมบัติ', 'Eiem Sombat Market', 32, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.33.2', 10, 'ศรีนครินทร์ซอย 24', 'Srinagarindra 24 Allay', 33, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.34.2', 10, 'ตรงข้ามธัญญาพาร์ค', 'Opposite Thanya Park', 34, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.35.2', 10, 'หมู่บ้านนราสิริ', 'Narasiri Village', 35, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.36.2', 10, 'ซอยศรีนครินทร์ 18', 'Srinakarin 18 Allay', 36, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.37.2', 10, 'ก่อนแยกพัฒนาการ', 'Before Phatthanakan Intersection', 37, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.38.2', 10, 'สถานีหัวหมาก', 'Hua Mak Station', 38, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.39.2', 10, 'โรงพยาบาลสมิติเวช ศรีนครินทร์', 'Samitivej Srinakarin Hospital', 39, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.40.2', 10, 'โรงเรียนอนุบาลชตูิมา', 'Chutima Kindergarten', 40, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.41.2', 10, 'ต่างระดับกรุงเทพกรีฑา (ขาเข้า)', 'Krungthep Kreetha Interchange (Arrival)', 41, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.42.2', 10, 'กรีนสปอร์ต', 'Green Sport', 42, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.43.2', 10, 'ตรงข้ามซอยศรีนครินทร์ 1', 'Opposite Srinakarin 1 Allay', 43, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.44.2', 10, 'ตลาดบางกะปิ', 'Bang Kapi Market', 44, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.45.2', 10, 'สถานีตำรวจลาดพร้าว', 'Police Station Lat Phrao', 45, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.46.2', 10, 'หมวดการทางบางกะปิ', 'Bang Kapi Highway Division', 46, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.47.2', 10, 'โรงเรียนบ้านบางกะปิ', 'Ban Bang Kapi School', 47, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.48.2', 10, 'ตรงข้ามการเคหะแห่งชาติ', 'Opposite National Housing Authority', 48, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.49.2', 10, 'ซอยนวมินทร์ 17', 'Nawamin 17', 49, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.50.2', 10, 'ตรงข้ามสนามกีฬาคลองจั่น', 'Opposite Khlong Chan Stadium', 50, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.51.2', 10, 'ตรงข้ามหมู่บ้านแฮปปี้แลนด์', 'Opposite Happyland Village', 51, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.52.2', 10, 'ตรงข้ามหมู่บ้านเสนาวิลล่า 84 / หมู่บ้านสินธร', 'Opposite Sena Villa Village 84 / Sinthorn Village', 52, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.53.2', 10, 'หมู่บ้านบ้านเรา แฮปปี้แลนด์', 'Ban Rao Happyland Village', 53, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.54.2', 10, 'ลุมพินีเซ็นเตอร์แฮปปี้แลนด์ (อาคาร C)', 'Lumpini Center Happyland (Building C)', 54, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.55.2', 10, 'ตลาดแฮปปี้แลนด์ (ฝั่งสาย 1)', 'Happyland Market (Sai 1 Side)', 55, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.56.2', 10, 'ก่อนแยกแฮปปี้แลนด์', 'Before Happyland Junction', 56, 'Outbound', 'Yes');

-- ==========================
-- S1 line
-- ==========================
INSERT INTO Station_stop VALUES ('S1.1.1', 11, 'ท่าปล่อยรถ สนามหลวง (53/1 59 503)', 'Bus depot, Sanam Luang (53/1 59 503)', 1, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.1', 11, 'โรงละครแห่งชาติ', 'National Theater', 2, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.3.1', 11, 'พระอาทิตย์', 'Phra Athit', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.4.1', 11, 'ท่าพระอาทิตย์', 'Phra Athit Pier', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.5.1', 11, 'แยกบางลำพู', 'Banglumphu Intersection', 5, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.6.1', 11, 'วัดชนะสงคราม', 'Chanasongkram Temple', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.7.1', 11, 'กองสลาก', 'Government Lottery Office', 7, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.8.1', 11, 'แยกคอกวัว', 'Khok Wua Intersection', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.9.1', 11, 'อนุสาวรีย์ประชาธิปไตย (ศึกษาภัณฑ์)', 'Democracy Monument (Suksapan)', 9, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.10.1', 11, 'ตรงข้ามนิทรรศน์รัตนโกสินทร์', 'Opposite Rattanakosin Exhibition Hall', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.11.1', 11, 'ตรงข้ามการบินไทย หลานหลวง', 'Opposite Thai Airways, Lan Luang', 11, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.12.1', 11, 'วัดแคนางเลิ้ง', 'Kae Nang Loeng Temple', 12, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.13.1', 11, 'สำนักงานสถิติแห่งชาติ', 'National Statistical Office', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.14.1', 11, 'โรงพยาบาลมิชชั่น, ตลาดมหานาค (ตรงข้ามบ้านมนังคศิลา)', 'Mission Hospital, Mahanak Market (opposite Ban Manangkasila)', 14, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.15.1', 11, 'ท่าอากาศยานสุวรรณภูมิ (อาคารผู้โดยสาร ชั้น 1 ประตู 7)', 'Suvarnabhumi Airport (Passenger Terminal, 1st Floor, Gate 7)', 15, 'Inbound', 'No');

INSERT INTO Station_stop VALUES ('S1.1.2', 11, 'ท่าอากาศยานสุวรรณภูมิ (อาคารผู้โดยสาร ชั้น 1 ประตู 7)', 'Suvarnabhumi Airport (Passenger Terminal, 1st Floor, Gate 7)', 1, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.2', 11, 'ตรงข้ามโรงพยาบาลมิชชั่น, ตลาดมหานาค (บ้านมนังคศิลา)', 'Opposite Mission Hospital, Mahanak Market (Ban Manangkasila)', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.3.2', 11, 'ตรงข้ามสำนักงานสถิติแห่งชาติ', 'Opposite National Statistical Office', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.4.2', 11, 'ตรงข้ามวัดแคนางเลิ้ง', 'Opposite Kae Nang Loeng Temple', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.5.2', 11, 'ท่าเรือผ่านฟ้า', 'Phan Fa Pier', 5, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.6.2', 11, 'วัดราชนัดดา, ลานพลับพลามหาเจษฎาบดินทร์', 'Ratchanadda Temple, Phlapphla Maha Jessadabodin', 6, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.7.2', 11, 'อนุสาวรีย์ประชาธิปไตย (ตรงข้าม ศึกษาภัณฑ์)', 'Democracy Monument (Opposite Suksapan)', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.8.2', 11, 'ที่ทำการไปรษณีย์ไทย สาขาบางลำพู', 'Banglampu Post Office', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.9.2', 11, 'วัดชนะสงคราม', 'Chanasongkram Temple', 9, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.10.2', 11, 'หอศิลป์เจ้าฟ้า', 'National Gallery', 10, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.11.2', 11, 'ตรงข้ามโรงละครแห่งชาติ', 'Opposite National Theater', 11, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.12.2', 11, 'ท่าปล่อยรถ สนามหลวง (53/1 59 503)', 'Bus depot, Sanam Luang (53/1 59 503)', 12, 'Outbound', 'No');