-- stop_id, line_id, stop_name_th, stop_name_en, sequence_no, direction, is_fare_point

-- ==========================
-- Light Green Line
-- ==========================
INSERT INTO station_stop VALUES ('E1.1.1', 1, 'ชิดลม', 'Chit Lom', 1, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('CEN.1.2', 1, 'สยาม', 'Siam', 2, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N1.1.3', 1, 'ราชเทวี', 'Ratchathewi', 3, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N2.1.4', 1, 'พญาไท', 'Phayathai', 4, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N3.1.5', 1, 'อนุสาวรีย์ชัยสมรภูมิ', 'Victory Monument', 5, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N4.1.6', 1, 'สนามเป้า', 'Sanam Pao', 6, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N5.1.7', 1, 'อารีย์', 'Ari', 7, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N6.1.8', 1, 'เสนาร่วม', 'Sena Ruam', 8, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N7.1.9', 1, 'สะพานควาย', 'Saphan Khwai', 9, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N8.1.10', 1, 'หมอชิต', 'Mo Chit', 10, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N9.1.11', 1, 'ห้าแยกลาดพร้าว', 'Ha Yaek Lat Phrao', 11, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N10.1.12', 1, 'พหลโยธิน 24', 'Phahon Yothin 24', 12, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N11.1.13', 1, 'รัชโยธิน', 'Ratchayothin', 13, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N12.1.17', 1, 'เสนานิคม', 'Sena Nikhom', 14, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N13.1.15', 1, 'มหาวิทยาลัยเกษตรศาสตร์', 'Kasetsart University', 15, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N14.1.16', 1, 'กรมป่าไม้', 'Royal Forest Department', 16, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('N15.1.17', 1, 'บางบัว', 'Bang Bua', 17, 'Inbound', NULL);

INSERT INTO station_stop VALUES ('N15.2.1', 1, 'บางบัว', 'Bang Bua', 1, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N14.2.2', 1, 'กรมป่าไม้', 'Royal Forest Department', 2, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N13.2.3', 1, 'มหาวิทยาลัยเกษตรศาสตร์', 'Kasetsart University', 3, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N12.2.4', 1, 'เสนานิคม', 'Sena Nikhom', 4, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N11.2.5', 1, 'รัชโยธิน', 'Ratchayothin', 5, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N10.2.6', 1, 'พหลโยธิน 24', 'Phahon Yothin 24', 6, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N9.2.7', 1, 'ห้าแยกลาดพร้าว', 'Ha Yaek Lat Phrao', 7, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N8.2.8', 1, 'หมอชิต', 'Mo Chit', 8, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N7.2.9', 1, 'สะพานควาย', 'Saphan Khwai', 9, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N6.2.10', 1, 'เสนาร่วม', 'Sena Ruam', 10, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N5.2.11', 1, 'อารีย์', 'Ari', 11, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N4.2.12', 1, 'สนามเป้า', 'Sanam Pao', 12, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N3.2.13', 1, 'อนุสาวรีย์ชัยสมรภูมิ', 'Victory Monument', 13, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N2.2.14', 1, 'พญาไท', 'Phayathai', 14, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('N1.2.15', 1, 'ราชเทวี', 'Ratchathewi', 15, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('CEN.2.16', 1, 'สยาม', 'Siam', 16, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('E1.2.17', 1, 'ชิดลม', 'Chit Lom', 17, 'Outbound', NULL);

-- ==========================
-- Blue Line
-- ==========================
INSERT INTO station_stop VALUES ('BL13.1.1', 2, 'สวนจตุจักร', 'Chatuchak Park', 1, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('BL14.1.2', 2, 'พหลโยธิน', 'Phahon Yothin', 2, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('BL15.1.3', 2, 'ลาดพร้าว', 'Lat Phrao', 3, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('BL16.1.4', 2, 'รัชดาภิเษก', 'Ratchadaphisek', 4, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('BL17.1.5', 2, 'สุทธิสาร', 'Sutthisan', 5, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('BL18.1.6', 2, 'ห้วยขวาง', 'Huai Khwang', 6, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('BL19.1.7', 2, 'ศูนย์วัฒนธรรมแห่งประเทศไทย', 'Thailand Culture Centre', 7, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('BL20.1.8', 2, 'พระราม 9', 'Phra Ram 9', 8, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('BL21.1.9', 2, 'เพชรบุรี', 'Phetchaburi', 9, 'Inbound', NULL);

INSERT INTO station_stop VALUES ('BL21.2.1', 2, 'เพชรบุรี', 'Phetchaburi', 1, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('BL20.2.2', 2, 'พระราม 9', 'Phra Ram 9', 2, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('BL19.2.3', 2, 'ศูนย์วัฒนธรรมแห่งประเทศไทย', 'Thailand Culture Centre', 3, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('BL18.2.4', 2, 'ห้วยขวาง', 'Huai Khwang', 4, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('BL17.2.5', 2, 'สุทธิสาร', 'Sutthisan', 5, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('BL16.2.6', 2, 'รัชดาภิเษก', 'Ratchadaphisek', 6, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('BL15.2.7', 2, 'ลาดพร้าว', 'Lat Phrao', 7, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('BL14.2.8', 2, 'พหลโยธิน', 'Phahon Yothin', 8, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('BL13.2.9', 2, 'สวนจตุจักร', 'Chatuchak Park', 9, 'Outbound', NULL);

-- ==========================
-- Yellow Line
-- ==========================
INSERT INTO station_stop VALUES ('YL01.1.1', 3, 'ลาดพร้าว', 'Lat Phrao', 1, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL02.1.2', 3, 'ภาวนา', 'Phawana', 2, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL03.1.3', 3, 'โชคชัย 4', 'Chok Chai 4', 3, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL04.1.4', 3, 'ลาดพร้าว 71', 'Lat Phrao 71', 4, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL05.1.5', 3, 'ลาดพร้าว 83', 'Lat Phrao 83', 5, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL06.1.6', 3, 'มหาดไทย', 'Mahat Thai', 6, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL07.1.7', 3, 'ลาดพร้าว 101', 'Lat Phrao 101', 7, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL08.1.8', 3, 'บางกะปิ', 'Bang Kapi', 8, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL09.1.9', 3, 'แยกลำสาลี', 'Yaek Lam Sali', 9, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL10.1.10', 3, 'ศรีกรีฑา', 'Si Kritha', 10, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL11.1.11', 3, 'หัวหมาก', 'Hua Mak', 11, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL12.1.12', 3, 'กลันตัน', 'Kalantan', 12, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL13.1.13', 3, 'ศรีนุช', 'Si Nut', 13, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL14.1.14', 3, 'ศรีนครินทร์ 38', 'Srinagarindra 38', 14, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL15.1.15', 3, 'สวนหลวง ร.9', 'Suan Luang Rama IX', 15, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('YL16.1.16', 3, 'ศรีอุดม', 'Si Udom', 16, 'Inbound', NULL);

INSERT INTO station_stop VALUES ('YL16.2.1', 3, 'ศรีอุดม', 'Si Udom', 1, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL15.2.2', 3, 'สวนหลวง ร.9', 'Suan Luang Rama IX', 2, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL14.2.3', 3, 'ศรีนครินทร์ 38', 'Srinagarindra 38', 3, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL13.2.4', 3, 'ศรีนุช', 'Si Nut', 4, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL12.2.5', 3, 'กลันตัน', 'Kalantan', 5, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL11.2.6', 3, 'หัวหมาก', 'Hua Mak', 6, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL10.2.7', 3, 'ศรีกรีฑา', 'Si Kritha', 7, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL09.2.8', 3, 'แยกลำสาลี', 'Yaek Lam Sali', 8, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL08.2.9', 3, 'บางกะปิ', 'Bang Kapi', 9, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL07.2.10', 3, 'ลาดพร้าว 101', 'Lat Phrao 101', 10, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL06.2.11', 3, 'มหาดไทย', 'Mahat Thai', 11, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL05.2.12', 3, 'ลาดพร้าว 83', 'Lat Phrao 83', 12, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL04.2.13', 3, 'ลาดพร้าว 71', 'Lat Phrao 71', 13, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL03.2.14', 3, 'โชคชัย 4', 'Chok Chai 4', 14, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL02.2.15', 3, 'ภาวนา', 'Phawana', 15, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('YL01.2.16', 3, 'ลาดพร้าว', 'Lat Phrao', 16, 'Outbound', NULL);

-- ==========================
-- SRT Line
-- ==========================
INSERT INTO station_stop VALUES ('SRT6.1.1', 4, 'อโศก', 'Asoke', 1, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT4.1.2', 4, 'พญาไท', 'Phayathai', 2, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT5.1.3', 4, 'มักกะสัน', 'Makkasan', 3, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT9.1.4', 4, 'หัวหมาก', 'Hua Mak', 4, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT8.1.5', 4, 'สุขุมวิท 71', 'Sukhumvit 71', 5, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT7.1.6', 4, 'คลองตัน', 'Khlong Tan', 6, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT10.1.7', 4, 'บ้านทับช้าง', 'Ban Thap Chang', 7, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT15.1.8', 4, 'คลองหลวงแพ่ง', 'Khlong Luang Phaeng', 8, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT14.1.9', 4, 'หัวตะเข้', 'Hua Takhe', 9, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT13.1.10', 4, 'พระจอมเกล้า', 'Phra Chom Klao', 10, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT12.1.11', 4, 'ลาดกระบัง', 'Lat Krabang', 11, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('SRT11.1.12', 4, 'ซอยวัดลานบุญ', 'Soi Wat Lan Bun', 12, 'Inbound', NULL);

INSERT INTO station_stop VALUES ('SRT11.2.1', 4, 'ซอยวัดลานบุญ', 'Soi Wat Lan Bun', 1, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT12.2.2', 4, 'ลาดกระบัง', 'Lat Krabang', 2, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT13.2.3', 4, 'พระจอมเกล้า', 'Phra Chom Klao', 3, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT14.2.4', 4, 'หัวตะเข้', 'Hua Takhe', 4, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT15.2.5', 4, 'คลองหลวงแพ่ง', 'Khlong Luang Phaeng', 5, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT10.2.6', 4, 'บ้านทับช้าง', 'Ban Thap Chang', 6, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT7.2.7', 4, 'คลองตัน', 'Khlong Tan', 7, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT8.2.8', 4, 'สุขุมวิท 71', 'Sukhumvit 71', 8, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT9.2.9', 4, 'หัวหมาก', 'Hua Mak', 9, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT5.2.10', 4, 'มักกะสัน', 'Makkasan', 10, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT4.2.11', 4, 'พญาไท', 'Phayathai', 11, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('SRT6.2.12', 4, 'อโศก', 'Asoke', 12, 'Outbound', NULL);

-- ==========================
-- ARL Line
-- ==========================
INSERT INTO station_stop VALUES ('A8.1.1', 5, 'พญาไท', 'Phayathai', 1, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('A7.1.2', 5, 'ราชปรารภ', 'Ratchprarop', 2, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('A6.1.3', 5, 'มักกะสัน', 'Makkasan', 3, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('A5.1.4', 5, 'รามคำแหง', 'Ramkhamhaeng', 4, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('A4.1.5', 5, 'หัวหมาก', 'Hua Mak', 5, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('A3.1.6', 5, 'บ้านทับช้าง', 'Ban Thap Chang', 6, 'Inbound', NULL);
INSERT INTO station_stop VALUES ('A2.1.7', 5, 'ลาดกระบัง', 'Lat Krabang', 7, 'Inbound', NULL);

INSERT INTO station_stop VALUES ('A2.2.1', 5, 'ลาดกระบัง', 'Lat Krabang', 1, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('A3.2.2', 5, 'บ้านทับช้าง', 'Ban Thap Chang', 2, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('A4.2.3', 5, 'หัวหมาก', 'Hua Mak', 3, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('A5.2.4', 5, 'รามคำแหง', 'Ramkhamhaeng', 4, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('A6.2.5', 5, 'มักกะสัน', 'Makkasan', 5, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('A7.2.6', 5, 'ราชปรารภ', 'Ratchprarop', 6, 'Outbound', NULL);
INSERT INTO station_stop VALUES ('A8.2.7', 5, 'พญาไท', 'Phayathai', 7, 'Outbound', NULL);

-- ==========================
-- 2-38 Line
-- ==========================
INSERT INTO station_stop VALUES ('2-38.1.1', 6, 'เดอะมอลล์บางกะปิ', 'The Mall Bangkapi', 1, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.2', 6, 'แม็คโครลาดพร้าว', 'Makro Lat Phrao', 2, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.3', 6, 'ซอยลาดพร้าว 142', 'Lat Phrao 142 Alley', 3, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.4', 6, 'ซอยลาดพร้าว 136', 'Lat Phrao 136 Alley', 4, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.5', 6, 'ตรงข้ามโรงพยาบาลเวชธานี', 'Opposite Vejthani Hospital', 5, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.6', 6, 'ซอยลาดพร้าว 130', 'Lat Phrao 130 Alley', 6, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.7', 6, 'ก่อนแยกลาดพร้าว 101', 'Before Lat Phrao101 Intersection', 7, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.8', 6, 'ซอยลาดพร้าว 126', 'Lat Phrao 126 Alley', 8, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.9', 6, 'ซอยลาดพร้าว 122', 'Lat Phrao 122 Alley', 9, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.10', 6, 'ตรงข้ามโรงพยาบาลลาดพร้าว', 'Opposite Lat Phrao Hospital', 10, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.11', 6, 'ตรงข้ามฟู้ดแลนด์', 'Opposite Food Land', 11, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.12', 6, 'ซอยลาดพร้าว 114, โรงเรียนบางกอกศึกษา', 'Lat Phrao 114 Alley', 12, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.13', 6, 'ซอยลาดพร้าว 112', 'Lat Phrao 112 Alley', 13, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.14', 6, 'ซอยลาดพร้าว 106', 'Lat Phrao 106 Alley', 14, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.15', 6, 'ตรงข้ามบิ๊กซีลาดพร้าว', 'Opposite Big C Lat Phrao', 15, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.16', 6, 'ซอยลาดพร้าว 90', 'Lat Phrao 90 Alley', 16, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.17', 6, 'ตรงข้ามซอยลาดพร้าว 71', 'Opposite Lat Phrao 71 Alley', 17, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.18', 6, 'ซอยลาดพร้าว 80', 'Lat Phrao 80 Alley', 18, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.19', 6, 'ตรงข้ามไปรษณีย์ลาดพร้าว', 'Opposite Post Office Lat Phrao', 19, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.20', 6, 'ตรงข้ามศึกษาภัณฑ์ลาดพร้าว', 'Opposite Suksaphan Lat Phrao', 20, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.21', 6, 'ซอยลาดพร้าว 62', 'Lat Phrao 62 Alley', 21, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.22', 6, 'ตรงข้ามตลาดโชคชัย 4', 'Opposite Chokchai 4 Market', 22, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.23', 6, 'ตรงข้ามตลาดสะพาน 2', 'Opposite Saphan 2 Market', 23, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.24', 6, 'โรงเรียนพิบูลอุปถัมภ์', 'Pibool Uppatham School', 24, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.25', 6, 'ตรงข้ามซอยภาวนา', 'Opposite Phawana Alley', 25, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.26', 6, 'ซอยลาดพร้าว 42', 'Lat Phrao 42 Alley', 26, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.27', 6, 'ซอยลาดพร้าว 40, ศิริชัยไกย่าง', 'Lat Phrao 40 Alley', 27, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.28', 6, 'ซอยลาดพร้าว 34', 'Lat Phrao 34 Alley', 28, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.29', 6, 'ตรงข้ามบ้านกลางเมือง ลาดพร้าว', 'Baan Klang Muang', 29, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.30', 6, 'ซอยลาดพร้าว 28', 'Lat Phrao 28 Alley', 30, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.31', 6, 'MRT ลาดพร้าว (ทางออก 1)', 'MRT Lat Phrao Station (Exit 1)', 31, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.32', 6, 'ซอยลาดพร้าว 20', 'Lat Phrao 20 Alley', 32, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.33', 6, 'ซอยลาดพร้าว 14', 'Lat Phrao 14 Alley', 33, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.34', 6, 'ตรงข้ามบิ๊กซีเอ็กซ์ตร้า ลาดพร้าว', 'Opposite Big C Extra Lat Phrao', 34, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.35', 6, 'ไปรษณีย์สามแยกลาดพร้าว', 'Sam Yaek Lat Phrao Post Office', 35, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.36', 6, 'ซอยลาดพร้าว 8', 'Lat Phrao 8 Alley', 36, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.37', 6, 'ตรงข้ามยูเนี่ยนมอลล์', 'Opposite Union Mall', 37, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.38', 6, 'MRT พหลโยธิน (ทางออก 2)', 'MRT Phahon Yothin Station (Exit 2)', 38, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.39', 6, 'ธนาคารทหารไทยธนชาต สำนักงานใหญ่', 'TTB Headquarter', 39, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.40', 6, 'ตรงข้ามสวนจตุจักร (จุดที่ 2)', 'Opposite Chatuchak Park (Stop 2)', 40, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.41', 6, 'กรมการขนส่งทางบก', 'Department Of Land Transport', 41, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.42', 6, 'แยกกำแพงเพชร', 'Kamphaeng Phet Junction', 42, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.43', 6, 'ตรงข้ามวัดไผ่ตัน', 'Opposite Phai Tan Temple', 43, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.44', 6, 'BTS สะพานควาย (ทางออก2)', 'BTS Saphan Khwai (Exit 2)', 44, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.45', 6, 'สถานีตำรวจบางซื่อ', 'Police Station Bangsue', 45, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.46', 6, 'ซอยสายลม', 'Sai Lom', 46, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.47', 6, 'ลา วิลล่า อารีย์', 'La Villa Ari', 47, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.48', 6, 'ตรงข้ามซอยราชครู', 'Opposite Ratchakru Alley', 48, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.49', 6, 'ซอยพหลโยธิน 2', 'Phahonyothin 2 Alley', 49, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.50', 6, 'BTS สนามเป้า (ทางออก4)', 'BTS Sanampao (Exit 4)', 50, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.51', 6, 'สถานีวิทยุโทรทัศน์กองทัพบก ช่อง 5', 'Royal Thai Army Radio And Television Channel 5', 51, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.52', 6, 'ตรงข้ามซอยลือชา', 'Opposite Luecha Alley', 52, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.53', 6, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะราชวิถี)', 'Victory Monument (Ratchawithi)', 53, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.54', 6, 'โรงพยาบาลเด็ก', 'Children Hospital', 54, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.55', 6, 'โรงเรียนสอนคนตาบอดกรุงเทพ', 'The Bangkok School For the Blind', 55, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.56', 6, 'องค์การเภสัชกรรม', 'Government Pharmaceutical Organization', 56, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.57', 6, 'กระทรวงอุตสาหกรรม', 'Ministry Of Industry', 57, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.58', 6, 'กรมทางหลวง', 'Department Of Highway', 58, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.59', 6, 'หลังแยกเสาวนี', 'After Saowani Intersection', 59, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.60', 6, 'ก่อนแยกยมราช', 'Before Yommarat Intersection', 60, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.61', 6, 'บ้านมนังคศิลา', 'Baan Manangkasila', 61, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.62', 6, 'หลังแยกสะพานขาว', 'After Saphan Khao Intersection', 62, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.63', 6, 'ตรงข้ามวัดสุนทรธรรมทาน', 'Opposite Sunthon Thammathan Temple', 63, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.64', 6, 'ตรงข้ามวัดสระเกศ (ภูเขาทอง)', 'Opposite Saket Temple (Phu Khao Thong)', 64, 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.1.65', 6, 'วรจักร', 'Worachak', 65, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.66', 6, 'วัดตึก', 'Chaichana Songkhram Temple (Wat Tuek)', 66, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.67', 6, 'สำเพ็ง (ฝั่งจักรวรรดิ)', 'Sampeng (Chakrawat Side)', 67, 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.1.68', 6, 'ท่ารถสะพานพุทธ', 'Saphan Phut Bus Station', 68, 'Inbound', 'Yes');

INSERT INTO station_stop VALUES ('2-38.2.1', 6, 'ท่ารถสะพานพุทธ', 'Saphan Phut Bus Station', 1, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.2', 6, 'ปากคลองตลาด', 'Pak Khlong Market', 2, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.3', 6, 'คลองคูเมืองเดิม (ฝั่งอัษฎางค์)', 'Khlong Khu Mueang Doem (Atsadang Side)', 3, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.4', 6, 'MRT สามยอด', 'MRT Sam Yot Station', 4, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.5', 6, 'แยกเอสเอบี', 'S.A.B. Intersection', 5, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.6', 6, 'ตรงข้ามคลองถม (ฝั่งวรจักร)', 'Opposite Khlong Thom (Worachak Side)', 6, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.7', 6, 'ตลาดวรจักร', 'Worachak Market', 7, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.8', 6, 'ก่อนแยกแม้นศรี', 'Before Maen Si Intersection', 8, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.9', 6, 'วัดสระเกศ (ภูเขาทอง)', 'Saket Temple (Golden Mountain)', 9, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.10', 6, 'วัดสุนทรธรรมทาน', 'Sunthon Thammathan Temple', 10, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.11', 6, 'ก่อนแยกสะพานขาว', 'Before Saphan Khao Intersection', 11, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.12', 6, 'โรงพยาบาลมิชชั่น (ฝั่งหลานหลวง)', 'Mission Hospital (Lan Luang Side)', 12, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.13', 6, 'หลังแยกยมราช', 'After Yommarat Intersection', 13, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.14', 6, 'ก่อนแยกเสาวนี', 'Before Saowani Intersection', 14, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.15', 6, 'กระทรวงการต่างประเทศ', 'Ministry Of Foreign Affairs', 15, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.16', 6, 'มหาวิทยาลัยมหิดล (คณะวิทยาศาสตร์)', 'Mahidol University (Faculty Of Science)', 16, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.17', 6, 'โรงพยาบาลรามาธิบดี', 'Ramathibodi Hospital', 17, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.18', 6, 'วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า', 'Phramongkutklao College Of Medicine', 18, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.19', 6, 'โรงพยาบาลพระมงกุฎเกล้า', 'Phramongkutklao Hospital', 19, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.20', 6, 'ตรงข้ามโรงพยาบาลเด็ก', 'Opposite Children Hospital', 20, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.21', 6, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะพหลโยธิน)', 'Victory Monument (Phahon Yothin)', 21, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.22', 6, 'ซอยลือชา', 'Lue Cha Alley', 22, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.23', 6, 'โรงพยาบาลพญาไท 2', 'Phyathai 2 Hospital', 23, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.24', 6, 'BTS สนามเป้า (ทางออก1)', 'BTS Sanampao (Exit 1)', 24, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.25', 6, 'BTS สนามเป้า (ทางออก3)', 'BTS Sanampao (Exit 3)', 25, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.26', 6, 'ซอยราชครู', 'Ratchakhru Alley', 26, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.27', 6, 'ซอยอารีย์', 'Ari Alley', 27, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.28', 6, 'กองบัญชาการตำรวจตระเวนชายแดน', 'Border Patrol Police Bureau', 28, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.29', 6, 'ตรงข้ามสถานีตำรวจบางซื่อ', 'Opposite Bangsue Police Station', 29, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.30', 6, 'BTS สะพานควาย (ทางออก1)', 'BTS Saphan Khwai (Exit 1)', 30, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.31', 6, 'วัดไผ่ตัน', 'Phaiton Temple', 31, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.32', 6, 'สวนจตุจักร (จุดที่ 1)', 'Chatuchak Park (Stop 1)', 32, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.33', 6, 'ตรงข้ามธนาคารทหารไทยธนชาต สำนักงานใหญ่', 'Opposite TTB Headquarter', 33, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.34', 6, 'MRT พหลโยธิน (ทางออก3)', 'MRT Phahonyothin (Exit 3)', 34, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.35', 6, 'ยูเนี่ยนมอลล์', 'Union Mall', 35, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.36', 6, 'บ้านพร้อมพรรณ', 'Baan Promphan', 36, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.37', 6, 'บิ๊กซีเอ็กซ์ตร้า ลาดพร้าว', 'Big C Extra Lat Phrao', 37, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.38', 6, 'ซอยลาดพร้าว 15', 'Lat Phrao 15 Alley', 38, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.39', 6, 'MRT ลาดพร้าว (ทางออก 3)', 'MRT Lat Phrao Station (Exit 3)', 39, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.40', 6, 'ซอยลาดพร้าว 25', 'Lat Phrao 25 Alley', 40, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.41', 6, 'สถานีดับเพลิงลาดพร้าว', 'Lat Phrao Fire Station', 41, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.42', 6, 'ซอยลาดพร้าว 35/1', 'Lat Phrao 35/1 Alley', 42, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.43', 6, 'ซอยภาวนา', 'Phawana Alley', 43, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.44', 6, 'ตรงข้ามโรงเรียนพิบูลอุปถัมภ์', 'Opposite Phibool Uppatham School', 44, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.45', 6, 'ตลาดสะพาน 2', 'Saphan 2 Market', 45, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.46', 6, 'สถานีตำรวจโชคชัย', 'Police Station Chokchai', 46, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.47', 6, 'ตลาดโชคชัย 4', 'Chok Chai 4 Market', 47, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.48', 6, 'ซอยลาดพร้าว 57', 'Lat Phrao 57 Alley', 48, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.49', 6, 'ศึกษาภัณฑ์ลาดพร้าว', 'Suksapan Panit Lat Phrao', 49, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.50', 6, 'ไปรษณีย์ลาดพร้าว', 'Post Office Lat Phrao', 50, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.51', 6, 'ซอยลาดพร้าว 67/1', 'Lat Phrao 67/1 Alley', 51, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.52', 6, 'ซอยลาดพร้าว 71', 'Lat Prao 71 Alley', 52, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.53', 6, 'ซอยลาดพร้าว 79', 'Lat Phrao 79 Alley', 53, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.54', 6, 'บิ๊กซีลาดพร้าว', 'Big C Lat Phrao', 54, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.55', 6, 'ตรงข้ามซอยลาดพร้าว 106', 'Opposite Lat Phrao 106 Alley', 55, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.56', 6, 'ซอยลาดพร้าว 89', 'Lat Phrao 89 Alley', 56, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.57', 6, 'ซอยลาดพร้าว 93', 'Lat Phrao 93 Alley', 57, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.58', 6, 'โรงพยาบาลลาดพร้าว', 'Lat Phrao Hospital', 58, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.59', 6, 'ซอยลาดพร้าว 97', 'Lat Phrao 97 Alley', 59, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.60', 6, 'ซอยลาดพร้าว 99', 'Lat Phrao 99 Alley', 60, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.61', 6, 'ซอยลาดพร้าว 101', 'Lat Phrao 101 Alley', 61, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.62', 6, 'ซอยลาดพร้าว 101/2', 'Lat Phrao 101/2 Alley', 62, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.63', 6, 'ซอยลาดพร้าว 107', 'Lat Phrao 107 Alley', 63, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.64', 6, 'โรงพยาบาลเวชธานี', 'Wetthani Hospital', 64, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.65', 6, 'ซอยลาดพร้าว 113', 'Lat Phrao 113 Alley', 65, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.66', 6, 'ตรงข้ามแม็คโครลาดพร้าว', 'Opposite Makro Lat Phrao', 66, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.67', 6, 'หลังแยกแฮปปี้แลนด์', 'After Happyland Intersection', 67, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.68', 6, 'ตรงข้ามตลาดแฮปปี้แลนด์ (ฝั่งสาย 1)', 'Opposite Happyland Market (Sai 1 Side)', 68, 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.69', 6, 'ลุมพินีเซ็นเตอร์แฮปปี้แลนด์ (อาคาร D)', 'Lumpini Center Happyland (Building D)', 69, 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.2.70', 6, 'หมู่บ้านแฮปปี้แลนด์', 'Happyland Village', 70, 'Outbound', 'Yes');

-- ==========================
-- 13 line
-- ==========================
INSERT INTO Station_stop VALUES ('13.1.1', 7, 'อู่คลองเตย', 'Klongtoey Bus Depot', 1, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.1.2', 7, 'ตรงข้ามเขตการเดินรถที่4', 'Bus Zone 4', 2, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.3', 7, 'โรงเรียนคอนแวนต์, ตลาดปีนัง', 'Talat Pinang', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.4', 7, 'การไฟฟ้าคลองเตย', 'Electricity Toei', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.5', 7, 'ลุมพินีทาวเวอร์ (ตรงข้ามบ่อนกาย)', 'Lumpini Tower (Opposite Brun Kai)', 5, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.1.6', 7, 'สวนลุมพินีป้ายแรก (เข้าเมือง)', 'First stop at Lumphini Park (Entering the city)', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.7', 7, 'ตรงข้ามซอยพระเจน', 'Opposite Phra Chen Alley', 7, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.8', 7, 'ตรงข้ามสถานีตำรวจลุมพินี', 'Opposite Lumpini Police Station', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.9', 7, 'อาคารสินธร, ตรงข้ามสถานฑูตอเมริกา', 'Sindhorn Building, opposite the American Embassy', 9, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.1.10', 7, 'แยกเพลนิจิต, โรงแรมเซ็นเตอร์พ้อยท์', 'Ploenchit Intersection, Center Point Hotel', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.11', 7, 'ซอยต้นสน, ตรงข้ามสถานฑูตอังกฤษ', 'Tonson Alley', 11, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.12', 7, 'เซ็นทรัลเวิลด์', 'Central World', 12, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.1.13', 7, 'อินทราสแควร์ประตูน้ำ', 'Indra Square Pratunam', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.14', 7, 'ซอยรางน้ำ', 'Rang Nam Alley', 14, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.15', 7, 'ตรงข้ามวัดตะพาน', 'Opposite Taphan Temple', 15, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.16', 7, 'สำนักงาน ป.ป.ส.', 'ONCB Office', 16, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.1.17', 7, 'รร.พิบูลประชาสรรค์', 'Piboon Prachasan School', 17, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.18', 7, 'สถาบันราชานุกูล', 'Rajanukul Institute', 18, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.19', 7, 'แยกประชาสงเคราะห์', 'Pracha Songkhro Intersection', 19, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.20', 7, 'ประชาสงเคราะห์1', 'Pracha Songkhro 1', 20, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.21', 7, 'สำนักงานเคหะดินแดง', 'Dindaeng Housing Office', 21, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.22', 7, 'ตลาดดินแดง', 'Dindaeng Market', 22, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.23', 7, 'โรงเรียนวชิรศิษฐ์', 'Wichutit School', 23, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.1.24', 7, 'ศูนย์บริการสาธารณสุข 4', 'Health Center 4', 24, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.25', 7, 'ตรงข้ามโรงเรียนพร้มพรรณวิทยา', 'Opposite Promphanwittaya School', 25, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.26', 7, 'ซอยประชาสงเคราะห์21', 'Pracha Songkhro 21', 26, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.27', 7, 'ซอยประชาสงเคราะห์23', 'Pracha Songkhro 23', 27, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.28', 7, 'วัดพรหมวงศาราม', 'Phrom Wong Saram Temple', 28, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.29', 7, 'TVC คอนโดมิเนียม', 'TVC Condominium', 29, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.30', 7, 'ตรงข้ามโรงเรียนอำนวย', 'Opposite Amnuayvid School', 30, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.1.31', 7, 'ท่ารถห้วยขวาง', 'Huai Khwang port', 31, 'Inbound', 'Yes');

INSERT INTO Station_stop VALUES ('13.2.1', 7, 'ท่ารถห้วยขวาง', 'Huai Khwang port', 1, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.2', 7, 'สถานีดับเพลิงห้วยขวาง, สาธารณสุข52', 'Huai Khwang Fire Station, Public Health 52', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.3', 7, 'ตลาดห้วยขวางหลังโรงเรียนสามเสนนอก', 'Huai Khwang Market behind Samsen Nok School', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.4', 7, 'ธนาคารกรุงไทยสาขาห้วยขวาง', 'Krungthai Bank Huai Khwang Branch', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.5', 7, 'หอนาฬิกาห้วยขวาง', 'Huai Khwang Clock Tower', 5, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.6', 7, 'ตรงข้ามทีวีซีคอนโดมิเนียม', 'Opposite TVC Condominium', 5, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.7', 7, 'ตรงข้ามวัดพรหมวงศาราม', 'Opposite Phrom Wong Saram Temple', 6, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.8', 7, 'ดีดีทาวเวอร์', 'Dd Tower', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.9', 7, 'ซอยประชาสงเคราะห์16-18', 'Pracha Songkhro 16-18', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.10', 7, 'โรงเรียนพร้มพรรณวิทยา', 'Promphanwittaya School', 9, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.11', 7, 'ตรงข้ามศูนย์บริการสาธารณสุข 4', 'Opposite Health Center 4', 10, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.12', 7, 'ตรงข้ามโรงเรียนวชิรศิษฐ์', 'Opposite Wichutit School', 11, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.13', 7, 'ตรงข้ามตลาดดินแดง', 'Opposite Dindaeng Market', 12, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.14', 7, 'ตรงข้ามสำนักงานเคหะดินแดง', 'Opposite the Din Daeng Housing Office', 13, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.15', 7, 'ประชาสงเคราะห์2', 'Pracha Songkhro 2', 14, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.16', 7, 'แฟลตดินแดง (ป้าย1)', 'Dindaeng Housing (Stop.1)', 15, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.17', 7, 'แฟลตดินแดง (ป้าย2)', 'Dindaeng Housing (Stop.2)', 16, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.18', 7, 'ตรงข้ามโรงเรียนพิบูลประชาสรรค์', 'Opposite Piboon Prachasan School', 17, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.19', 7, 'ตลาดศรีวานิช', 'Sriwanit Market', 18, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.20', 7, 'ตรงข้ามซอยรางน้ำ', 'Opposite Rang Nam Alley', 19, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.21', 7, 'ตรงข้ามอินทราสแควร์ประตูน้ำ', 'Opposite Indra Square Pratunam', 20, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.22', 7, 'บิ๊กซีราชดำริ', 'Big C Rajdamri', 21, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.23', 7, 'เพนนินซูลาพลาซ่า', 'Peninsula Plaza', 22, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.24', 7, 'BTS ราชดำริ (ทางออก2)', 'BTS Ratchadamri (Exit 2)', 23, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.25', 7, 'สถาบันสอนภาษา', 'AUA Language Institute', 24, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.26', 7, 'หลังสวน1 อาคารปาร์คเพลส', 'Lang Suan 1, Park Place', 25, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.27', 7, 'หลังสวน2', 'Lang Suan 2', 26, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.28', 7, 'สมาคมสร้างคุณค่าในประเทศไทย', 'Association of Value Creation in Thailand', 27, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.29', 7, 'ซอยพระเจน', 'Phra Chen Alley', 28, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.30', 7, 'สวนลุมไนท์บาซาร์', 'Suan Lum Night Bazaar', 29, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.31', 7, 'บ่อนกาย', 'Brun Kai', 30, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.32', 7, 'ตลาดคลองเตย (ถนนสุนทรโกษา ขาออก)', 'Talat Khlong Toei', 31, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.33', 7, 'ตรงข้ามสโมสรการท่าเรือ', 'Opposite Port F.C.', 32, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.34', 7, 'ตรงข้ามสนามกีฬาการท่าเรือ', 'Opposite Sanamkila Kan Tharuea', 33, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.35', 7, 'ซอยคั่วพริก ก่อนถึงแยกกรมศุลกากร', 'Kua Phrik Alley, before Customs Department Intersection', 34, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.2.36', 7, 'อู่คลองเตย', 'Klongtoey Bus Depot', 35, 'Outbound', 'No');

-- ==========================
-- 2-53 line 
-- ==========================
INSERT INTO station_stop VALUES ('2-53.1.1', 8, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะดินแดง)', 'Victory Monument (Din Daeng)', 1, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.2', 8, 'ซอยลือชา', 'Lue Cha Alley', 2, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.3', 8, 'โรงพยาบาลพญาไท 2', 'Phyathai 2 Hospital', 3, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.4', 8, 'BTS สนามเป้า (ทางออก 1)', 'BTS Sanampao (Exit 1)', 4, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.5', 8, 'BTS สนามเป้า (ทางออก 3)', 'BTS Sanampao (Exit 3)', 5, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.6', 8, 'ซอยราชครู', 'Ratchakhru Alley', 6, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.7', 8, 'ซอยอารีย์', 'Ari Alley', 7, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.8', 8, 'กองบัญชาการตำรวจตระเวนชายแดน', 'Border Patrol Police Bureau', 8, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.9', 8, 'ตรงข้าม สถานีตำรวจบางซื่อ', 'Opposite Bangsue Police Station', 9, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.10', 8, 'BTS สะพานควาย (ทางออก 1)', 'BTS Saphan Khwai (Exit 1)', 10, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.11', 8, 'วัดไผ่ตัน', 'Phaiton Temple', 11, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.12', 8, 'สวนจตุจักร (จุดที่1)', 'Chatuchak Park (Stop 1)', 12, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.13', 8, 'สวนจตุจักร (จุดที่2)', 'Chatuchak Park (Stop 2)', 13, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.14', 8, 'ตรงข้ามธนาคารทหารไทยธนชาต สำนักงานใหญ่', 'Opposite TTB Headquarter', 14, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.15', 8, 'สวนรถไฟ', 'Rot Fai Park', 15, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.16', 8, 'สำนักงานใหญ่ ปตท.', 'PTT Headquarter', 16, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.17', 8, 'ซอยวิภาวดีรังสิต 13', 'Vibhavadi Rangsit 13 Alley', 17, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.18', 8, 'ตรงข้ามตรีเพชรอีซูซุ', 'Opposite Tri Petch Isuzu', 18, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.19', 8, 'ตรงข้ามเอสซีบี ปาร์ค พลาซ่า', 'Opposite SCB Park Plaza', 19, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.20', 8, 'แยกรัชโยธิน', 'Ratchayothin Intersection', 20, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.21', 8, 'ซอยรัชดาภิเษก 42', 'Ratchadaphisek 42 Alley', 21, 'Clockwise', 'No'); 
INSERT INTO station_stop VALUES ('2-53.1.22', 8, 'ซอยเสือใหญ่', 'Suea Yai Alley', 22, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.23', 8, 'มหาวิทยาลัยราชภัฏจันทรเกษม', 'Chandrakasem Rajabhat University', 23, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.24', 8, 'สำนักงาน คปภ.', 'Office Of Insurance Commission', 24, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.25', 8, 'กรมส่งเสริมการค้าระหว่างประเทศ', 'Department Of International Trade Promotion', 25, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.26', 8, 'อาคารโอลิมเปีย', 'Olympia Thai Tower', 26, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.27', 8, 'ตรงข้ามโรงเรียนปัญจทรัพย์', 'Opposite Panchasap School', 27, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.28', 8, 'บุญถาวร รัชดาภิเษก (ขาเข้า)', 'Boonthavorn Ratchadaphisek (Inbound)', 28, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.29', 8, 'ปรีชา คอมเพล็กซ์', 'Preecha Complex', 29, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.30', 8, 'อาคารเมืองไทย-ภัทร', 'Muang Thai-Phat Building', 30, 'Clockwise', 'NO');
INSERT INTO station_stop VALUES ('2-53.1.31', 8, 'ตรงข้ามโรงเรียนเตรียมอุดมศึกษาน้อมเกล้า กนุนที', 'Opposite Triam Udom Suksa Nomklao (Kunnatee School)', 31, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.32', 8, 'MRT ห้วยขวาง (ทางออก 1)', 'MRT Huai Khwang (Exit 1)', 32, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.33', 8, 'โรงแรมสวิสโซเทล กรุงเทพฯ รัชดา', 'Swissotel Bangkok Ratchada', 33, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.34', 8, 'โรงเรียนเตรียมอุดมศึกษาพัฒนาการ รัชดา', 'Triam Udom Suksa Pattanakarn Ratchada School', 34, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.35', 8, 'ตรงข้ามบิ๊กซีเอ็กซ์ตร้า รัชดาภิเษก', 'Opposite Big C Extra Ratchadaphisek', 35, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.36', 8, 'ตรงข้ามเอสพลานาด รัชดาภิเษก', 'Opposite Esplanade Ratchadaphisek', 36, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.37', 8, 'ตรงข้ามสถานทูตจีน', 'Opposite Embassy of China', 37, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.38', 8, 'ตรงข้ามตลาดอยู่เจริญ', 'Opposite Yoo Charoen Market', 38, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.39', 8, 'ตรงข้ามตลาดขวัญพัฒนา', 'Opposite Khwan Phatthana Market', 39, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.40', 8, 'โบสถ์แม่พระฟาติมา', 'Fatima Catholic Church', 40, 'Clockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.1.41', 8, 'แฟลตดินแดง (อาคาร 7)', 'Din Daeng Flat (Building 7)', 41, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.42', 8, 'แฟลตดินแดง (อาคาร 5)', 'Din Daeng Flat (Building 5)', 42, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.43', 8, 'ตรงข้ามโรงเรียนพิบูลประชาสรรค์', 'Opposite Piboon Prachasan School', 43, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.44', 8, 'ตรงข้ามสำนักงาน ป.ป.ส.', 'Opposite Office Of the Narcotics Control Board', 44, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.45', 8, 'สวนสันติภาพ', 'Santiphap Park', 45, 'Clockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.1.46', 8, 'อนุสาวรีย์ชัยสมรภูมิ (พหลโยธิน)', 'Victory Monument (Din Daeng)', 46, 'Clockwise', 'Yes');

INSERT INTO station_stop VALUES ('2-53.2.1', 8, 'อนุสาวรีย์ชัยสมรภูมิ (พหลโยธิน) (ขาเข้า)', 'Victory Monument (Phahonyothin In)', 1, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.2.2', 8, 'ตรงข้ามสวนสันติภาพ', 'Opposite SantiphapPark', 2, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.3', 8, 'สำนักงาน ป.ป.ส. โรงเรียนพิบูลประชาสรรค์', 'Office of the Narcotics Control Board Prachasan School Piboon', 3, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.4', 8, 'สถาบันราชานุกูล', 'Rajanukul Institute', 4, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.5', 8, 'ตรงข้ามโบสถ์แม่พระฟาติมา', 'Opposite Fatima Catholic Church', 5, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.2.6', 8, 'ตลาดขวัญพัฒนา', 'Khwan Phatthana Market', 6, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.7', 8, 'ตลาดอยู่เจริญ', 'Yoo Charoen Market', 7, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.8', 8, 'ฟอร์จูนทาวน์', 'Fortune Town', 8, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.9', 8, 'สถานทูตจีน', 'Embassy of China', 9, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.10', 8, 'เอสพลานาด รัชดาภิเษก', 'Esplanade Ratchadaphisek', 10, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.11', 8, 'บิ๊กซีเอ็กซ์ตร้า รัชดาภิเษก', 'Big C Extra Ratchadaphisek', 11, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.2.12', 8, 'โรงเรียนเตรียมอุดมศึกษาพัฒนาการ รัชดา', 'Triam Udom Suksa Pattanakarn Ratchada School', 12, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.13', 8, 'โรงแรมดิ เอมเมอรัลด์', 'The Emerald Hotel', 13, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.14', 8, 'MRT ห้วยขวาง (ทางออก 3)', 'MRT Huai Khwang (Exit 3)', 14, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.15', 8, 'MRT ห้วยขวาง (ทางออก 4)', 'MRT Huai Khwang (Exit 4)', 15, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.16', 8, 'โรงเรียนเตรียมอุดมศึกษาน้อมเกล้า กุนนที', 'Triam Udom Suksa Nomklao Kunnatee School', 16, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.2.17', 8, 'อาคารกลาสเฮ้าส์ รัชดา', 'Glas Haus Ratchada Building', 17, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.18', 8, 'สถานีตำรวจสุทธิสาร', 'Police Office Sutthisan', 18, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.2.19', 8, 'บุญถาวรรัชดาภิเษก (ขาออก)', 'Boonthavorn Ratchadaphisek (Outbound)', 19, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.20', 8, 'โรงเรียนปัญจทรัพย์', 'Panchasap School', 20, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.21', 8, 'ศาลาแขวงพระนครเหนือ', 'Bangkok North Municipal Court', 21, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.22', 8, 'ศาลอาญา', 'Criminal Court', 22, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.23', 8, 'ตรงข้ามมหาวิทยาลัยราชภัฏจันทรเกษม', 'Opposite Chandrakasem Rajabhat University', 23, 'Counterclockwise', 'Yes');
INSERT INTO station_stop VALUES ('2-53.2.24', 8, 'ซอยเสือใหญ่', 'Suea Yai alley', 24, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.25', 8, 'ตรงข้ามโรงเรียนสุวรรณศึกษา', 'Opposite Suan Yai', 25, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.26', 8, 'ตรงข้ามซอยรัชดาภิเษก 42', 'Opposite Ratchadaphisek 42 Alley', 26, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.27', 8, 'สถานีดำารวจพหลโยธิน', 'Phahon Yothin Police Station', 27, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.28', 8, 'เอสซีบี ปาร์ค พลาซ่า', 'SCB Park Plaza', 28, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.29', 8, 'ตรีเพชรอีซูซุ', 'Tri Petch Isuzu', 29, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.30', 8, 'โรงเรียนหอวัง', 'Horwang School', 30, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.31', 8, 'ธนาคารทหารไทยธนชาต สำนักงานใหญ่', 'Ttb Headquarter', 31, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.32', 8, 'ตรงข้ามสวนจตุจักร (จุดที่ 2)', 'Opposite Chatuchak Park (Stop 2)', 32, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.33', 8, 'กรมการขนส่งทางบก', 'Department Of Land Transport', 33, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.34', 8, 'แยกกำแพงเพชร', 'Kamphaeng Phet Junction', 34, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.35', 8, 'ตรงข้ามวัดไผ่ตัน', 'Opposite WAT Phai Tan', 35, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.36', 8, 'Bts สะพานควาย (ทางออก2)', 'Bts Saphan Khwai (Exit 2)', 36, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.37', 8, 'สถานีดำารวจบางซื่อ', 'Bangsue Police Station', 37, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.38', 8, 'ซอยสายลม', 'Sai Lom alley', 38, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.39', 8, 'ลา วิลล่า อารีย์', 'La Villa Ari', 39, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.40', 8, 'ตรงข้ามซอยราชครุ', 'Opposite Ratchakru Alley', 40, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.41', 8, 'ซอยพหลโยธิน 2', 'Phahonyothin 2 alley', 41, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.42', 8, 'Bts สนามเป้า (ทางออก4)', 'BTS Sanampao (Exit 4)', 42, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.43', 8, 'สถานีวิทยุโทรทัศน์กองทัพบก ช่อง 5', 'Royal Thai Army Radio And Television Channel 5', 43, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.44', 8, 'ตรงข้ามซอยลือชา', 'Opposite Soi Lucha', 44, 'Counterclockwise', 'No');
INSERT INTO station_stop VALUES ('2-53.2.45', 8, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะดินแดง)', 'Victory Monument (Din Daeng)', 45, 'Counterclockwise', 'Yes');

-- ==========================
-- 12 line 
-- ==========================
INSERT INTO Station_stop VALUES ('12.1.1', 9, 'สถานีดับเพลิงห้วยขวาง, สาธารณสุข 52', 'Huai Khwang Fire Station, Public Health 52', 1, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.1.2', 9, 'โรงเรียนสามเสนนอก', 'Samsen Nok School', 2, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.1.3', 9, 'ธนาคารกรุงไทย สาขาห้วยขวาง', 'Krung Thai Bank (Huai Khwang)', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.4', 9, 'หอนาฬิกาห้วยขวาง', 'Huai Khwang Clock Tower', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.5', 9, 'ตรงข้ามทีวีซี คอนโดมิเนียม', 'Opposite TVC Condominium', 5, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.6', 9, 'ตรงข้ามวัดพรหมวงศาราม', 'Opposite Phrom Wong Saram Temple', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.7', 9, 'ดีดี ทาวเวอร์', 'DD Tower', 7, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.8', 9, 'ซอยประชาสงเคราะห์ 16-18', 'Pracha Songkhro 16-18 Alley', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.9', 9, 'โรงเรียนพร้อมพรรณวิทยา', 'Promphanwittaya School', 9, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.10', 9, 'ตรงข้ามศูนย์บริการสาธารณสุข 4', 'Opposite Health Center 4', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.11', 9, 'ตรงข้ามโรงเรียนวิชูทิตย์', 'Opposite Wichutit School', 11, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.1.12', 9, 'ตรงข้ามตลาดดินแดง', 'Opposite Dindaeng Market', 12, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.13', 9, 'ตรงข้ามสำนักงานเคหะดินแดง', 'Opposite Dindaeng Housing Office', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.14', 9, 'ประชาสงเคราะห์ 2', 'Pracha Songkhro 2', 14, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.15', 9, 'แฟลตดินแดง (ป้าย 1)', 'Dindaeng Housing Stop 1', 15, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.16', 9, 'แฟลตดินแดง (ป้าย 2)', 'Dindaeng Housing Stop 2', 16, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.17', 9, 'ตรงข้ามโรงเรียนพิบูลประชาสรรค์', 'Opposite Piboon Prachasan School', 17, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.18', 9, 'ตลาดศรีวานิช', 'Sriwanit Market', 18, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.1.19', 9, 'สวนสันติภาพ', 'Santiphap Park', 19, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.20', 9, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะราชวิถี)', 'Victory Monument (Ratchawithi)', 20, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.21', 9, 'โรงพยาบาลเด็ก', 'Children Hospital', 21, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.22', 9, 'โรงเรียนสอนคนตาบอดกรุงเทพ', 'Bangkok School for the Blind', 22, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.1.23', 9, 'บ้านราชวิถี (ฝั่งพระราม 6)', 'Ban Ratchawithi (Rama VI side)', 23, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.24', 9, 'สำนักงานประปา สาขาแม้นศรี', 'Maensir Waterworks Office', 24, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.25', 9, 'ซอยสุโขทัย 1, 3', 'Sukho Thai 1, 3 Alley', 25, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.26', 9, 'ซอยสุโขทัย 5', 'Sukho Thai 5 Alley', 26, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.27', 9, 'ตรงข้ามโรงเรียนสุโขทัย', 'Opposite Sukhothai School', 27, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.28', 9, 'ตรงข้ามสำนักงานเขตดุสิต', 'Opposite Dusit District Office', 28, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.29', 9, 'ตรงข้ามสภาสตรีแห่งประเทศไทย', 'Opposite Women Council of Thailand', 29, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.30', 9, 'ตรงข้ามโรงเรียนพันธะวัฒนา', 'Opposite Pantawattana School', 30, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.1.31', 9, 'ร้านศิลปาชีพ 905', 'Silapacheep Shop 905', 31, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.32', 9, 'สวนรื่นฤดี, ตรงข้ามกองอำนวยการรักษาความมั่นคงในราชอาณาจักร', 'Suan Ruen-Rudi, Opposite Internal Security Command', 32, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.33', 9, 'มหาวิทยาลัยราชภัฏสวนดุสิต (แยกการเรือน)', 'Suan Dusit Rajabhat University (Home Economics Intersection)', 33, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.34', 9, 'ตรงข้ามกรมป้องกันและบรรเทาสาธารณภัย', 'Opposite Department of Disaster Prevention and Mitigation', 34, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.35', 9, 'พระตำหนักวังสวนกุหลาบ', 'Vimanmek Mansion', 35, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.36', 9, 'ครุสภา', 'Teachers Council of Thailand', 36, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.1.37', 9, 'วัดมกุฏกษัตริย์', 'Makutkasat Temple', 37, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.38', 9, 'กองบัญชาการกองทัพบก', 'Royal Thai Army', 38, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.39', 9, 'โรงแรม เดอ ม็อค (ตรงข้ามวัดตรีทศเทพ)', 'Hotel De Moc (Opposite Tri Thotsathep Temple)', 39, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.40', 9, 'สะพานวันชาติ', 'Wan Chat Bridge', 40, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.41', 9, 'ศาลาว่าการกรุงเทพมหานคร', 'Bangkok City Hall', 41, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.1.42', 9, 'เสาชิงชา', 'Sao Chingcha', 42, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.43', 9, 'วัดสุทัศน์', 'Suthat Temple', 43, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.44', 9, 'ก่อนสี่กั๊กพระยาศรี', 'Before Si Kak Phraya Sri', 44, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.45', 9, 'หน่วยบัญชาการรักษาดินแดน', 'Territorial Defense Command', 45, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.46', 9, 'สวนเจ้าเชตุ', 'Chao Chet Park', 46, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('12.1.47', 9, 'โรงเรียนวัดราชบพิธ (ท่าปลายทาง ปากคลองตลาด)', 'Wat Rajabophit School (Terminus Pak Khlong Market)', 47, 'Inbound', 'Yes');

INSERT INTO Station_stop VALUES ('12.2.1', 9, 'โรงเรียนวัดราชบพิธ (ท่าปลายทาง ปากคลองตลาด)', 'Wat Rajabophit School (Terminus Pak Khlong Market)', 1, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.2', 9, 'พระพิพิธ (ตรงข้าม กรมที่ดิน)', 'Phra Phiphit (Opposite Department of Lands)', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.3', 9, 'บ้านหม้อ', 'Ban Mo', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.4', 9, 'ตรงข้ามวัดสุทัศน์, ร้านวิจิตรพาณิชย์', 'Opposite Suthat Temple, Vijit Panich Shop', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.5', 9, 'ตรงข้ามศาลาว่าการกรุงเทพมหานคร', 'Opposite Bangkok City Hall', 5, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.6', 9, 'โรงเรียนสตรีวิทยา', 'Satriwittaya School', 6, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.7', 9, 'วัดตรีทศเทพ', 'Tri Thotsathep Temple', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.8', 9, 'ตรงข้ามกองบัญชาการกองทัพบก', 'Opposite Royal Thai Army', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.9', 9, 'ตรงข้ามวัดมกุฏกษัตริย์', 'Opposite Makutkasat Temple', 9, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.10', 9, 'สำนักงานทรัพย์สินส่วนพระมหากษัตริย์ (ตรงข้าม ครุสภา)', 'Crown Property Bureau Office (Opposite Teachers Council)', 10, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.11', 9, 'โรงเรียนราชวินิต', 'Rajavinit School', 11, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.12', 9, 'กรมป้องกันและบรรเทาสาธารณภัย กระทรวงมหาดไทย', 'Department of Disaster Prevention and Mitigation, Ministry of Interior', 12, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.13', 9, 'มหาวิทยาลัยราชภัฏสวนดุสิต', 'Suan Dusit Rajabhat University', 13, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.14', 9, 'ซอยสวนอ้อย, กองอำนวยการรักษาความมั่นคงภายในราชอาณาจักร', 'Suan Oi Alley, Internal Security Command', 14, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.15', 9, 'พณิชยการสุโขทัย', 'Bangkok Health and Services Technological College', 15, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.16', 9, 'สภาสตรีแห่งประเทศไทย', 'Women Council of Thailand', 16, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.17', 9, 'สำนักงานเขตดุสิต', 'Dusit District Office', 17, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.18', 9, 'พรรคชาติพัฒนา (ถนนสุโขทัย)', 'Chart Pattana Party (Sukhothai Rd)', 18, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.19', 9, 'ตรงข้ามซอยสุโขทัย 5', 'Opposite Sukho Thai 5 Alley', 19, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.20', 9, 'ตรงข้ามซอยสุโขทัย 1', 'Opposite Sukho Thai 1 Alley', 20, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.21', 9, 'แยกสวรรคโลก (ขาเข้า)', 'Sawankhalok Intersection (Inbound)', 21, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.22', 9, 'บ้านราชวิถี', 'Ban Ratchawithi', 22, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.23', 9, 'วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า', 'Phramongkutklao College of Medicine', 23, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.24', 9, 'พระราชวังพญาไท', 'Phayathai Palace', 24, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.25', 9, 'ตรงข้ามโรงพยาบาลเด็ก', 'Opposite Children Hospital', 25, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.26', 9, 'อนุสาวรีย์ชัยสมรภูมิ (เกาะดินแดง)', 'Victory Monument (Din Daeng)', 26, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.27', 9, 'ตรงข้ามสวนสันติภาพ', 'Opposite Santiphap Park', 27, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.28', 9, 'สำนักงาน ป.ป.ส.', 'ONCB Office', 28, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.29', 9, 'โรงเรียนพิบูลประชาสรรค์', 'Piboon Prachasan School', 29, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.30', 9, 'สถาบันราชานุกูล', 'Rajanukul Institute', 30, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.31', 9, 'แยกประชาสงเคราะห์', 'Pracha Songkhro Intersection', 31, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.32', 9, 'ประชาสงเคราะห์ 1', 'Pracha Songkhro 1', 32, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.33', 9, 'สำนักงานเขตดินแดง', 'Dindaeng Housing Office', 33, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.34', 9, 'ตลาดดินแดง', 'Dindaeng Market', 34, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.35', 9, 'โรงเรียนวิชูทิตย์', 'Wichutit School', 35, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.36', 9, 'ศูนย์บริการสาธารณสุข 4', 'Health Center 4', 36, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.37', 9, 'ตรงข้ามโรงเรียนพร้อมพรรณวิทยา', 'Opposite Promphanwittaya School', 37, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.38', 9, 'ซอยประชาสงเคราะห์ 21', 'Pracha Songkhro 21', 38, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.39', 9, 'ซอยประชาสงเคราะห์ 23', 'Pracha Songkhro 23', 39, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.40', 9, 'วัดพรหมวงศาราม', 'Phrom Wong Saram Temple', 40, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.41', 9, 'ทีวีซีคอนโดมิเนียม', 'TVC Condominium', 41, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.42', 9, 'ตรงข้ามโรงเรียนอำนวย', 'Opposite Amnuay School', 42, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.43', 9, 'หอนาฬิกาห้วยขวาง, ศูนย์รับเลี้ยงเด็กห้วยขวาง', 'Huai Khwang Clock Tower, Huai Khwang Daycare Center', 43, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('12.2.44', 9, 'ตรงข้ามตลาดห้วยขวาง', 'Opposite Huay Kwang Market', 44, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('12.2.45', 9, 'สถานีดับเพลิงห้วยขวาง, สาธารณสุข 52', 'Huai Khwang Fire Station, Public Health 52', 45, 'Outbound', 'Yes');

-- ==========================
-- S5 line
-- ==========================
INSERT INTO Station_stop VALUES ('S5.1.1', 10, 'ก่อนแยกแฮปปี้แลนด์', 'Before Happyland Junction', 1, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.2', 10, 'แยกลําสาลี (ฝั่งศรีนครินทร์ขาออก)', 'Lam Sali Intersection (Srinakarin Side Outbound)', 2, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.3', 10, 'ซอยศรีนครินทร์ 1', 'Srinakarin 1 Alley', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.4', 10, 'โรงแรมเดอะแกรนด์โฟรว์งส์', 'The Grand Fourwings Hotel', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.5', 10, 'ต่างระดับกรุงเทพกรีฑา (ขาออก)', 'Krungthep Kreetha Interchange (Outbound)', 5, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.6', 10, 'ซอยศรีนครินทร์ 7', 'Srinakarin 7 Alley', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.7', 10, 'ตรงข้ามโรงพยาบาลสมิติเวช ศรีนครินทร์', 'Opposite Samitivej Srinakarin Hospital', 7, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.8', 10, 'ARL หัวหมาก', 'ARL Hua Mak Station', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.9', 10, 'หลังแยกพัฒนาการ', 'After Phatthanakan Intersection', 9, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.10', 10, 'ซอยศรีนครินทร์ 23', 'Srinakarin 23 Alley', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.11', 10, 'อาคารโมเดิร์นฟอร์ม', 'Modernform', 11, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.12', 10, 'ธัญญาพาร์ค', 'Thanya Park', 12, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.13', 10, 'อาคาร 21 ทาวเวอร์', 'Twenty One Tower', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.14', 10, 'ตรงข้ามตลาดเอี่ยมสมบัติ', 'Opposite Eiem Sombat Market', 14, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.15', 10, 'ตรงข้ามไปรษณีย์ไทย สาขาอ่อนนุช', 'Post Office Onnut', 15, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.16', 10, 'ตรงข้ามหมู่บ้านเสรี–อ่อนนุช', 'Opposite Baan Seri – Onnut', 16, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.17', 10, 'ต่างระดับอ่อนนุช', 'On Nut Interchange', 17, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.18', 10, 'ซอยอ่อนนุช 55', 'On Nut 55 Alley', 18, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.19', 10, 'ตรงข้ามรองเท้าเอสซีเอส', 'Opposite Scs Shoes', 19, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.20', 10, 'ซอยอ่อนนุช 55/2', 'On Nut 55/2 Alley', 20, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.21', 10, 'ตรงข้ามโลตัสอ่อนนุช 80', 'Opposite Lotus On Nut 80', 21, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.22', 10, 'สุเหร่าทางควาย', 'Surao Thang Kwai', 22, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.23', 10, 'หมู่บ้านชมเดือน 3', 'Chom Duean 3 Village', 23, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.24', 10, 'ซอยอ่อนนุช 63', 'On Nut 63 Alley', 24, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.25', 10, 'ซอยอ่อนนุช 65', 'On Nut 65 Alley', 25, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.26', 10, 'ตรงข้ามซอยอ่อนนุช 84', 'Opposite On Nut 84 Alley', 26, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.27', 10, 'วัดกระทุ่มเสือปลา', 'Krathum Suea Pla Temple', 27, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.28', 10, 'ซอยอ่อนนุช 67/3', 'On Nut 67/3 Alley', 28, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.29', 10, 'หลังแยกอ่อนนุช-สุขาภิบาล 2', 'After Onnut-Sukhapiban 2 Junction', 29, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.30', 10, 'ตรงข้ามโรงพยาบาลสิรินธร', 'Opposite Sirindhorn Hospital', 30, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.31', 10, 'ตลาดน้ำ-ชัย', 'Namchai Market', 31, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.32', 10, 'ตรงข้ามโรงเรียนประเวศพิทยาคาร', 'Opposite Prawet Pittayakhan School', 32, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.33', 10, 'โรงเรียนพร้อม', 'Prom School', 33, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.34', 10, 'วัดลานบุญ', 'Lan Bun Temple', 34, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.35', 10, 'ศูนย์บริการสาธารณสุข 46', 'Public Health Service Center 46', 35, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.36', 10, 'โฮมโปร ลาดกระบัง', 'Homepro-Lat Krabang', 36, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.37', 10, 'แม็คโคร ลาดกระบัง', 'Makro Lat Krabang', 37, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.38', 10, 'ซอยลาดกระบัง 1/7', 'Lat Krabang 1/7 Alley', 38, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.39', 10, 'ตรงข้ามหมู่บ้านเดอะยูโรเปี้ยน', 'Opposite The European Village', 39, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.40', 10, 'ตรงข้ามเขตปลอดอากร สุวรรณภูมิ (ประตู1) (จุดที่1)', 'Opposite Suvarnabhumi Airport Free Zone (Entrance 1) (Stop 1)', 40, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.1.41', 10, 'ครัวการบินไทย สุวรรณภูมิ', 'Suvarnabhumi Thai Catering', 41, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.42', 10, 'สถานีดับเพลิงสุวรรณภูมิ', 'Suvarnabhumi Fire Station', 42, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S5.1.43', 10, 'สนามบินสุวรรณภูมิ (ศูนย์การขนส่งสาธารณะ)', 'Public Transportation Center Of Suvarnabhumi Airport Stop', 43, 'Inbound', 'Yes');

INSERT INTO Station_stop VALUES ('S5.2.1', 10, 'สนามบินสุวรรณภูมิ (ศูนย์การขนส่งสาธารณะ)', 'Public Transportation Center Of Suvarnabhumi Airport Stop', 1, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.2', 10, 'ตรงข้ามอาคารที่พักเวร ฝรภ.สุวรรณภูมิ', 'Opposite Suvarnabhumi Official Residence Of Security Department', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.3', 10, 'LSG สกายเชฟส์', 'LSG Sky Chefs', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.4', 10, 'ตรงข้ามสถานีดับเพลิงสุวรรณภูมิ', 'Opposite the Fire Station Suvarnabhumi Airport', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.5', 10, 'การบินไทยสุวรรณภูมิ (ตึกปฏิบัติการภาคพื้นดิน) (จุดที่3)', 'Suvarnabhumi (TG Ground Operation Control Center)', 5, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.6', 10, 'เขตปลอดอากร สุวรรณภูมิ (ประตู1)', 'Suvarnabhumi Airport Free Zone (Entrance 1) (Stop 1)', 6, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.7', 10, 'ตรงข้ามวัดสังฆราชา', 'Opposite Sangkha Racha Temple', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.8', 10, 'ซอยลาดกระบัง 28', 'Lat Krabang 28 Alley', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.9', 10, 'หมู่บ้านเดอะยูโรเปี้ยน', 'The European Village', 9, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.10', 10, 'ซอยลาดกระบัง 24', 'Lat Krabang 24 Alley', 10, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.11', 10, 'เดอะพาราโซ่ ลาดกระบัง', 'The Paseo Mall, Lat Krabang', 11, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.12', 10, 'โรบินสัน ลาดกระบัง', 'Robinson Lifestyle Lat Krabang', 12, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.13', 10, 'ตรงข้ามศูนย์บริการสาธารณสุข 46', 'Opposite Public Health Service Center 46', 13, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.14', 10, 'ตรงข้ามวัดลานบุญ', 'Opposite Lan Boon Temple', 14, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.15', 10, 'หมู่บ้านไทยสมุทร ลาดกระบัง', 'Thai Samut Lat Krabang Village', 15, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.16', 10, 'โรงเรียนประเวศพิทยาคาร', 'Prawet Pittayakarn School', 16, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.17', 10, 'ตรงข้ามตลาดน้ำ-ชัย', 'Opposite Namchai Market', 17, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.18', 10, 'โรงพยาบาลสิรินธร', 'Sirindhorn Hospital', 18, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.19', 10, 'ก่อนแยกอ่อนนุช-สุขาภิบาล 2', 'Before Onnut-Sukhapiban 2 Junction', 19, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.20', 10, 'ซอยอ่อนนุช 88', 'On Nut 88 Alley', 20, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.21', 10, 'โรงงานขยะมูลฝอยอ่อนนุช', 'On Nut Incineration Plant', 21, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.22', 10, 'ซอยอ่อนนุช 84', 'On Nut 84 Alley', 22, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.23', 10, 'ซอยอ่อนนุช 82', 'On Nut 82 Alley', 23, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.24', 10, 'ตรงข้ามหมู่บ้านชมเดือน 3', 'Opposite Chom Duean 3 Village', 24, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.25', 10, 'ตรงข้ามสุเหร่าทางควาย', 'Opposite Surao Thang Kwai', 25, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.26', 10, 'เทสโก้โลตัสอ่อนนุช 80', 'Tesco Lotus On Nut 80', 26, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.27', 10, 'ซอยอ่อนนุช 78', 'On Nut 78 Alley', 27, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.28', 10, 'รองเท้าเอสซีเอส', 'Scs Shoes', 28, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.29', 10, 'ซอยอ่อนนุช 74/3', 'Seri-Onnut Village', 29, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.30', 10, 'หมู่บ้านเสรี-อ่อนนุช', 'Seri-Onnut Village', 30, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.31', 10, 'ไปรษณีย์อ่อนนุช', 'Post Office Onnut', 31, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.32', 10, 'ตลาดเอี่ยมสมบัติ', 'Eiem Sombat Market', 32, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.33', 10, 'ศรีนครินทร์ซอย 24', 'Srinagarindra 24 Alley', 33, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.34', 10, 'ตรงข้ามธัญญาพาร์ค', 'Opposite Thanya Park', 34, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.35', 10, 'หมู่บ้านนราสิริ', 'Narasiri Village', 35, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.36', 10, 'ซอยศรีนครินทร์ 18', 'Srinakarin 18 Alley', 36, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.37', 10, 'ก่อนแยกพัฒนาการ', 'Before Phatthanakan Intersection', 37, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.38', 10, 'สถานีหัวหมาก', 'Hua Mak Station', 38, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.39', 10, 'โรงพยาบาลสมิติเวช ศรีนครินทร์', 'Samitivej Srinakarin Hospital', 39, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.40', 10, 'โรงเรียนอนุบาลชตูิมา', 'Chutima Kindergarten', 40, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.41', 10, 'ต่างระดับกรุงเทพกรีฑา (ขาเข้า)', 'Krungthep Kreetha Interchange (Arrival)', 41, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.42', 10, 'กรีนสปอร์ต', 'Green Sport', 42, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.43', 10, 'ตรงข้ามซอยศรีนครินทร์ 1', 'Opposite Srinakarin 1 Alley', 43, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('S5.2.44', 10, 'ตลาดบางกะปิ', 'Bang Kapi Market', 44, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.45', 10, 'สถานีตำรวจลาดพร้าว', 'Police Station Lat Phrao', 45, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.46', 10, 'หมวดการทางบางกะปิ', 'Bang Kapi Highway Division', 46, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.47', 10, 'โรงเรียนบ้านบางกะปิ', 'Ban Bang Kapi School', 47, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.48', 10, 'ตรงข้ามการเคหะแห่งชาติ', 'Opposite National Housing Authority', 48, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.49', 10, 'ซอยนวมินทร์ 17', 'Nawamin 17', 49, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.50', 10, 'ตรงข้ามสนามกีฬาคลองจั่น', 'Opposite Khlong Chan Stadium', 50, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.51', 10, 'ตรงข้ามหมู่บ้านแฮปปี้แลนด์', 'Opposite Happyland Village', 51, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.52', 10, 'ตรงข้ามหมู่บ้านเสนาวิลล่า 84 / หมู่บ้านสินธร', 'Opposite Sena Villa Village 84 / Sinthorn Village', 52, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.53', 10, 'หมู่บ้านบ้านเรา แฮปปี้แลนด์', 'Ban Rao Happyland Village', 53, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.54', 10, 'ลุมพินีเซ็นเตอร์แฮปปี้แลนด์ (อาคาร C)', 'Lumpini Center Happyland (Building C)', 54, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.55', 10, 'ตลาดแฮปปี้แลนด์ (ฝั่งสาย 1)', 'Happyland Market (Sai 1 Side)', 55, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S5.2.56', 10, 'ก่อนแยกแฮปปี้แลนด์', 'Before Happyland Junction', 56, 'Outbound', 'Yes');

-- ==========================
-- S1 line
-- ==========================
INSERT INTO Station_stop VALUES ('S1.1.1', 11, 'ท่าปล่อยรถ สนามหลวง (53/1 59 503)', 'Bus depot, Sanam Luang (53/1 59 503)', 1, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.2', 11, 'โรงละครแห่งชาติ', 'National Theater', 2, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.3', 11, 'พระอาทิตย์', 'Phra Athit', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.4', 11, 'ท่าพระอาทิตย์', 'Phra Athit Pier', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.5', 11, 'แยกบางลำพู', 'Banglumphu Intersection', 5, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.6', 11, 'วัดชนะสงคราม', 'Chanasongkram Temple', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.7', 11, 'กองสลาก', 'Government Lottery Office', 7, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.8', 11, 'แยกคอกวัว', 'Khok Wua Intersection', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.9', 11, 'อนุสาวรีย์ประชาธิปไตย (ศึกษาภัณฑ์)', 'Democracy Monument (Suksapan)', 9, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.10', 11, 'ตรงข้ามนิทรรศน์รัตนโกสินทร์', 'Opposite Rattanakosin Exhibition Hall', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.11', 11, 'ตรงข้ามการบินไทย หลานหลวง', 'Opposite Thai Airways, Lan Luang', 11, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.12', 11, 'วัดแคนางเลิ้ง', 'Kae Nang Loeng Temple', 12, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.13', 11, 'สำนักงานสถิติแห่งชาติ', 'National Statistical Office', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.14', 11, 'โรงพยาบาลมิชชั่น, ตลาดมหานาค (ตรงข้ามบ้านมนังคศิลา)', 'Mission Hospital, Mahanak Market (opposite Ban Manangkasila)', 14, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('S1.1.15', 11, 'ท่าอากาศยานสุวรรณภูมิ (อาคารผู้โดยสาร ชั้น 1 ประตู 7)', 'Suvarnabhumi Airport (Passenger Terminal, 1st Floor, Gate 7)', 15, 'Inbound', 'No');

INSERT INTO Station_stop VALUES ('S1.2.1', 11, 'ท่าอากาศยานสุวรรณภูมิ (อาคารผู้โดยสาร ชั้น 1 ประตู 7)', 'Suvarnabhumi Airport (Passenger Terminal, 1st Floor, Gate 7)', 1, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.2', 11, 'ตรงข้ามโรงพยาบาลมิชชั่น, ตลาดมหานาค (บ้านมนังคศิลา)', 'Opposite Mission Hospital, Mahanak Market (Ban Manangkasila)', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.3', 11, 'ตรงข้ามสำนักงานสถิติแห่งชาติ', 'Opposite National Statistical Office', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.4', 11, 'ตรงข้ามวัดแคนางเลิ้ง', 'Opposite Kae Nang Loeng Temple', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.5', 11, 'ท่าเรือผ่านฟ้า', 'Phan Fa Pier', 5, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.6', 11, 'วัดราชนัดดา, ลานพลับพลามหาเจษฎาบดินทร์', 'Ratchanadda Temple, Phlapphla Maha Jessadabodin', 6, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.7', 11, 'อนุสาวรีย์ประชาธิปไตย (ตรงข้าม ศึกษาภัณฑ์)', 'Democracy Monument (Opposite Suksapan)', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.8', 11, 'ที่ทำการไปรษณีย์ไทย สาขาบางลำพู', 'Banglampu Post Office', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.9', 11, 'วัดชนะสงคราม', 'Chanasongkram Temple', 9, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.10', 11, 'หอศิลป์เจ้าฟ้า', 'National Gallery', 10, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.11', 11, 'ตรงข้ามโรงละครแห่งชาติ', 'Opposite National Theater', 11, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('S1.2.12', 11, 'ท่าปล่อยรถ สนามหลวง (53/1 59 503)', 'Bus depot, Sanam Luang (53/1 59 503)', 12, 'Outbound', 'No');