CREATE SEQUENCE stop_id_seq
START WITH 00000001
INCREMENT BY 1
MAXVALUE 9999999;
-- stop_id, line_id, stop_name_th, stop_name_en, sequence_no, is_fare_point

-- ==========================
-- 2-38 Line
-- ==========================
INSERT INTO station_stop VALUES ('2-38.1.1', 6, 1, 'เดอะมอลลบ์างกะปิ', 'The Mall Bangkapi', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.1', 6, 2, 'แม็คโครลาดพรา้ว', 'Makro Lat Phrao', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.3.1', 6, 3, 'ซอยลาดพรา้ว 142', 'Ladprao 142 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.4.1', 6, 4, 'ซอยลาดพรา้ว 136', 'Lat Phrao 136 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.5.1', 6, 5, 'ตรงขา้มโรงพยาบาลเวชธานี', 'Opposite Vejthani Hospital', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.6.1', 6, 6, 'ซอยลาดพรา้ว 130', 'Lat Phrao 130 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.7.1', 6, 7, 'กอ่นแยกลาดพรา้ว 101', 'Before Lat Phrao101 Intersection', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.8.1', 6, 8, 'ซอยลาดพรา้ว 126', 'Lat Phrao 126 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.9.1', 6, 9, 'ซอยลาดพรา้ว 122', 'Lat Phrao 122 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.10.1', 6, 10, 'ตรงขา้มโรงพยาบาลลาดพรา้ว', 'Opposite Lat Phrao Hospital', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.11.1', 6, 11, 'ตรงขา้มฟู้ดแลนด ์', 'Opposite Food Land', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.12.1', 6, 12, 'ซอยลาดพรา้ว 114,โรงเรยีนบางกอกศกึษา', 'Lat Phrao 114 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.13.1', 6, 13, 'ซอยลาดพรา้ว 112', 'Lat Phrao 112 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.14.1', 6, 14, 'ซอยลาดพรา้ว 106', 'Lat Phrao 106 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.15.1', 6, 15, 'ตรงขา้มบิ๊กซลีาดพรา้ว', 'Opposite Big C Ladprao', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.16.1', 6, 16, 'ซอยลาดพรา้ว 90', 'Lat Phrao 90 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.17.1', 6, 17, 'ตรงขา้มซอยลาดพรา้ว 71', 'Opposite Lat Phrao 71 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.18.1', 6, 18, 'ซอยลาดพรา้ว 80', 'Lat Phrao 80 Allay', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.19.1', 6, 19, 'ตรงขา้มไปรษณียล์าดพรา้ว', 'Opposite Post Office Lat Phrao', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.20.1', 6, 20, 'ตรงขา้มศกึษาภณัฑล์าดพรา้ว', 'Opposite Suksaphan Ladprao', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.21.1', 6, 21, 'ซอยลาดพรา้ว 62', 'Lat Phrao 62 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.22.1', 6, 22, 'ตรงขา้มตลาดโชคชยั 4', 'Opposite Chokchai 4 Market', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.23.1', 6, 23, 'ตรงขา้มตลาดสะพาน 2', 'Opposite Saphan 2 Market', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.24.1', 6, 24, 'โรงเรยีนพบิลูอปุถมัภ ์', 'Pibool Uppatham School', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.25.1', 6, 25, 'ตรงขา้มซอยภาวนา', 'Opposite Phawana Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.26.1', 6, 26, 'ซอยลาดพรา้ว 42', 'Lat Phrao 42 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.27.1', 6, 27, 'ซอยลาดพรา้ว 40,ศริชิยัไกย่า่ง', 'Lat Phrao 40 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.28.1', 6, 28, 'ซอยลาดพรา้ว 34', 'Lat Phrao 34 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.29.1', 6, 29, 'ตรงขา้มบา้นกลางเมอืง ลาดพรา้ว', 'Baan Klang Muang', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.30.1', 6, 30, 'ซอยลาดพรา้ว 28', 'Lat Phrao 28 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.31.1', 6, 31, 'MRT ลาดพรา้ว (ทางออก 1)', 'MRT Lat Phrao Station (Exit 1)', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.32.1', 6, 32, 'ซอยลาดพรา้ว 20', 'Lat Phrao 20 Allay', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.33.1', 6, 33, 'ซอยลาดพรา้ว 14', 'Lat Phrao 14 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.34.1', 6, 34, 'ตรงขา้มบิ๊กซเีอ็กซต์รา้ ลาดพรา้ว', 'Opposite Big C Extra Lat Phrao', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.35.1', 6, 35, 'ไปรษณียส์ามแยกลาดพรา้ว', 'Sam Yaek Lat Phrao Post Office', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.36.1', 6, 36, 'ซอยลาดพรา้ว 8', 'Lat Phrao 8 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.37.1', 6, 37, 'ตรงขา้มยเูนีย่นมอลล ์', 'Opposite Union Mall', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.38.1', 6, 38, 'MRT พหลโยธนิ (ทางออก 2)', 'MRT Phahon Yothin Station (Exit 2)', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.39.1', 6, 39, 'ธนาคารทหารไทยธนชาต สํานักงานใหญ ่', 'TTB Headquarter', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.40.1', 6, 40, 'ตรงขา้มสวนจตจัุกร (จดุที ่2)', 'Opposite Chatuchak Park (Stop 2)', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.41.1', 6, 41, 'กรมการขนสง่ทางบก', 'Department Of Land Transport', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.42.1', 6, 42, 'แยกกําแพงเพชร', 'Kamphaeng Phet Junction', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.43.1', 6, 43, 'ตรงขา้มวดัไผต่นั', 'Opposite Phai Tan Temple', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.44.1', 6, 44, 'BTS สะพานควาย (ทางออก2)', 'BTS Saphan Khwai (Exit 2)', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.45.1', 6, 45, 'สถานตํีารวจบางซือ่', 'Police Station Bangsue', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.46.1', 6, 46, 'ซอยสายลม', 'Sai Lom', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.47.1', 6, 47, 'ลา วลิลา่ อารยี ์', 'La Villa Ari', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.48.1', 6, 48, 'ตรงขา้มซอยราชคร ู', 'Opposite Ratchakru Allay', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.49.1', 6, 49, 'ซอยพหลโยธนิ 2', 'Phahonyothin 2 Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.50.1', 6, 50, 'BTS สนามเป้า (ทางออก4)', 'BTS Sanampao (Exit 4)', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.51.1', 6, 51, 'สถานวีทิยโุทรทศันก์องทพับก ชอ่ง 5', 'Royal Thai Army Radio And Television Channel 5', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.52.1', 6, 52, 'ตรงขา้มซอยลอืชา', 'Opposite Luecha Allay', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.53.1', 6, 53, 'อนุสาวรยีช์ยัสมรภมู ิ(เกาะราชวถิ)ี', 'Victory Monument (Ratchawithi)', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.54.1', 6, 54, 'โรงพยาบาลเด็ก', 'Children Hospital', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.55.1', 6, 55, 'โรงเรยีนสอนคนตาบอดกรงุเทพ', 'The Bangkok School For the Blind', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.56.1', 6, 56, 'องคก์ารเภสชักรรม', 'Government Pharmaceutical Organization', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.57.1', 6, 57, 'กระทรวงอตุสาหกรรม', 'Ministry Of Industry', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.58.1', 6, 58, 'กรมทางหลวง', 'Department Of Highway', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.59.1', 6, 59, 'หลงัแยกเสาวน ี', 'After Saowani Intersection', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.60.1', 6, 60, 'ก่อนแยกยมราช', 'Before Yommarat Intersection', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.61.1', 6, 61, 'บา้นมนังคศลิา', 'Baan Manangkasila', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.62.1', 6, 62, 'หลงัแยกสะพานขาว', 'After Saphan Khao Intersection', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.63.1', 6, 63, 'ตรงขา้มวดัสนุทรธรรมทาน', 'Opposite Sunthon Thammathan Temple', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.64.1', 6, 64, 'ตรงขา้มวดัสระเกศ (ภเูขาทอง)', 'Opposite Saket Temple (Phu Khao Thong)', 'Inbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.65.1', 6, 65, 'วรจักร', 'Worachak', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.66.1', 6, 66, 'วดัตกึ', 'Chaichana Songkhram Temple (Wat Tuek)', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.67.1', 6, 67, 'สําเพ็ง (ฝ่ังจักรวรรดิ)์', 'Sampeng (Chakrawat Side)', 'Inbound', 'No');
INSERT INTO station_stop VALUES ('2-38.68.1', 6, 68, 'ท่ารถสะพานพทุธ', 'Saphan Phut Bus Station', 'Inbound', 'Yes');

INSERT INTO station_stop VALUES ('2-38.1.2', 6, 1, 'ท่ารถสะพานพุทธ', 'Saphan Phut Bus Station', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.2.2', 6, 2, 'ปากคลองตลาด', 'Pak Khlong Market', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.3.2', 6, 3, 'คลองคูเมืองเดิม (ฝ่ังอัษฎางค์)', 'Khlong Khu Mueang Doem (Atsadang Side)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.4.2', 6, 4, 'MRT สามยอด', 'MRT Sam Yot Station', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.5.2', 6, 5, 'แยกเอสเอบี', 'S.A.B. Intersection', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.6.2', 6, 6, 'ตรงขา้มคลองถม (ฝ่ังวรจักร)', 'Opposite Khlong Thom (Worachak Side)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.7.2', 6, 7, 'ตลาดวรจักร', 'Worachak Market', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.8.2', 6, 8, 'กอ่นแยกแมน้ศร ี', 'Before Maen Si Intersection', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.9.2', 6, 9, 'วดัสระเกศ (ภเูขาทอง)', 'Saket Temple (Golden Mountain)', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.10.2', 6, 10, 'วดัสนุทรธรรมทาน', 'Sunthon Thammathan Temple', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.11.2', 6, 11, 'กอ่นแยกสะพานขาว', 'Before Saphan Khao Intersection', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.12.2', 6, 12, 'โรงพยาบาลมชิชัน่ (ฝ่ังหลานหลวง)', 'Mission Hospital (Lan Luang Side)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.13.2', 6, 13, 'หลงัแยกยมราช', 'After Yommarat Intersection', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.14.2', 6, 14, 'กอ่นแยกเสาวน ี', 'Before Saowani Intersection', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.15.2', 6, 15, 'กระทรวงการตา่งประเทศ', 'Ministry Of Foreign Affairs', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.16.2', 6, 16, 'มหาวทิยาลยัมหดิล (คณะวทิยาศาสตร)์', 'Mahidol University (Faculty Of Science)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.17.2', 6, 17, 'โรงพยาบาลรามาธบิด ี', 'Ramathibodi Hospital', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.18.2', 6, 18, 'วทิยาลยัแพทยศาสตร ์พระมงกฎุเกลา้', 'Phramongkutklao College Of Medicine', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.19.2', 6, 19, 'โรงพยาบาลพระมงกฎุเกลา้', 'Phramongkutklao Hospital', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.20.2', 6, 20, 'ตรงขา้มโรงพยาบาลเด็ก', 'Opposite Children Hospital', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.21.2', 6, 21, 'อนุสาวรยีช์ยัสมรภมู ิ(เกาะพหลโยธนิ)', 'Victory Monument (Phahon Yothin)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.22.2', 6, 22, 'ซอยลอืชา', 'Lue Cha Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.23.2', 6, 23, 'โรงพยาบาลพญาไท 2', 'Phyathai 2 Hospital', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.24.2', 6, 24, 'BTS สนามเป้า (ทางออก1)', 'BTS Sanampao (Exit 1)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.25.2', 6, 25, 'BTS สนามเป้า (ทางออก3)', 'BTS Sanampao (Exit 3)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.26.2', 6, 26, 'ซอยราชคร ู', 'Ratchakhru Allay', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.27.2', 6, 27, 'ซอยอารยี ์', 'Ari Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.28.2', 6, 28, 'กองบญัชาการตํารวจตระเวนชายแดน', 'Border Patrol Police Bureau', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.29.2', 6, 29, 'ตรงขา้มสถานตํีารวจบางซือ่', 'Opposite Bangsue Police Station', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.30.2', 6, 30, 'BTS สะพานควาย (ทางออก1)', 'BTS Saphan Khwai (Exit 1)', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.31.2', 6, 31, 'วดัไผต่นั', 'Phaiton Temple', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.32.2', 6, 32, 'สวนจตจัุกร (จดุที ่1)', 'Chatuchak Park (Stop 1)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.33.2', 6, 33, 'ตรงขา้มธนาคารทหารไทยธนชาต สํานักงาน ใหญ ่', 'Opposite TTB Headquarter', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.34.2', 6, 34, 'MRT พหลโยธนิ (ทางออก3)', 'MRT Phahonyothin (Exit 3)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.35.2', 6, 35, 'ยเูนีย่นมอลล ์', 'Union Mall', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.36.2', 6, 36, 'บา้นพรอ้มพันธุ ์', 'Baan Promphan', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.37.2', 6, 37, 'บิ๊กซเีอ็กซต์รา้ ลาดพรา้ว', 'Big C Extra Lat Phrao', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.38.2', 6, 38, 'ซอยลาดพรา้ว 15', 'Lat Phrao 15 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.39.2', 6, 39, 'MRT ลาดพรา้ว (ทางออก 3)', 'MRT Lat Phrao Station (Exit 3)', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.40.2', 6, 40, 'ซอยลาดพรา้ว 25', 'Lat Phrao 25 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.41.2', 6, 41, 'สถานดีบัเพลงิลาดพรา้ว', 'Lat Phrao Fire Station', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.42.2', 6, 42, 'ซอยลาดพรา้ว 35/1', 'Lat Phrao 35/1 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.43.2', 6, 43, 'ซอยภาวนา', 'Phawana Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.44.2', 6, 44, 'ตรงขา้มโรงเรยีนพบิลูอปุถมัภ ์', 'Opposite Phibool Uppatham School', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.45.2', 6, 45, 'ตลาดสะพาน 2', 'Saphan 2 Market', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.46.2', 6, 46, 'สถานตํีารวจโชคชยั', 'Police Station Chokchai', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.47.2', 6, 47, 'ตลาดโชคชยั 4', 'Chok Chai 4 Market', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.48.2', 6, 48, 'ซอยลาดพรา้ว 57', 'Lat Phrao 57 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.49.2', 6, 49, 'ศกึษาภณัฑล์าดพรา้ว', 'Suksapan Panit Lat Phrao', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.50.2', 6, 50, 'ไปรษณียล์าดพรา้ว', 'Post Office Lat Phrao', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.51.2', 6, 51, 'ซอยลาดพรา้ว 67/1', 'Lat Phrao 67/1 Allay', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.52.2', 6, 52, 'ซอยลาดพรา้ว 71', 'Lat Prao 71 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.53.2', 6, 53, 'ซอยลาดพรา้ว 79', 'Lat Phrao 79 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.54.2', 6, 54, 'บิ๊กซลีาดพรา้ว', 'Big C Lat Phrao', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.55.2', 6, 55, 'ตรงขา้มซอยลาดพรา้ว 106', 'Opposite Lat Phrao 106 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.56.2', 6, 56, 'ซอยลาดพรา้ว 89', 'Lat Phrao 89 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.57.2', 6, 57, 'ซอยลาดพรา้ว 93', 'Lat Phrao 93 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.58.2', 6, 58, 'โรงพยาบาลลาดพรา้ว', 'Lat Phrao Hospital', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.59.2', 6, 59, 'ซอยลาดพรา้ว 97', 'Lat Phrao 97 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.60.2', 6, 60, 'ซอยลาดพรา้ว 99', 'Lat Phrao 99 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.61.2', 6, 61, 'ซอยลาดพรา้ว 101', 'Lat Phrao 101 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.62.2', 6, 62, 'ซอยลาดพรา้ว 101/2', 'Lat Phrao 101/2 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.63.2', 6, 63, 'ซอยลาดพรา้ว 107', 'Lat Phrao 107 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.64.2', 6, 64, 'โรงพยาบาลเวชธาน ี', 'Wetthani Hospital', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.65.2', 6, 65, 'ซอยลาดพรา้ว 113', 'Lat Phrao 113 Allay', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.66.2', 6, 66, 'ตรงขา้มแม็คโครลาดพรา้ว', 'Opposite Makro Ladprao', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.67.2', 6, 67, 'หลงัแยกแฮปป้ีแลนด ์', 'After Happyland Intersection', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.68.2', 6, 68, 'ตรงขา้มตลาดแฮปป้ีแลนด ์(ฝ่ังสาย 1)', 'Opposite Happyland Market (Sai 1 Side)', 'Outbound', 'Yes');
INSERT INTO station_stop VALUES ('2-38.69.2', 6, 69, 'ลมุพนิเีซน็เตอรแ์ฮปป้ีแลนด ์(อาคาร D)', 'Lumpini Center Happyland (Building D)', 'Outbound', 'No');
INSERT INTO station_stop VALUES ('2-38.70.2', 6, 70, 'หมูบ่า้นแฮปป้ีแลนด ์', 'Happyland Village', 'Outbound', 'Yes');

-- ==========================
-- 13 line
-- ==========================
INSERT INTO Station_stop VALUES ('13.1.1', 6, 'อู่คลองเตย', 'Klongtoey Bus Depot', 1, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.1', 6, 'ตรงข้ามเขตการเดินรถที่4', 'Bus Zone 4', 2, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.3.1', 6, 'โรงเรียนคอนแวนต์, ตลาดปีนัง', 'Talat Pinang', 3, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.4.1', 6, 'การไฟฟ้าคลองเตย', 'Electricity Toei', 4, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.5.1', 6, 'ลุมพินีทาวเวอร์ (ตรงข้ามบ่อนกาย)', 'Lumpini Tower (Opposite Brun Kai)', 5, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.6.1', 6, 'สวนลุมพินีป้ายแรก (เข้าเมือง)', 'First stop at Lumphini Park (Entering the city)', 6, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.7.1', 6, 'ตรงข้ามซอยพระเจน', 'Opposite Phra Chen Allay', 7, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.8.1', 6, 'ตรงข้ามสถานีตำรวจลุมพินี', 'Opposite Lumpini Police Station', 8, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.9.1', 6, 'อาคารสินธร, ตรงข้ามสถานฑูตอเมริกา', 'Sindhorn Building, opposite the American Embassy', 9, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.10.1', 6, 'แยกเพลนิจิต, โรงแรมเซ็นเตอร์พ้อยท์', 'Ploenchit Intersection, Center Point Hotel', 10, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.11.1', 6, 'ซอยต้นสน, ตรงข้ามสถานฑูตอังกฤษ', 'Tonson Allay', 11, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.12.1', 6, 'เซ็นทรัลเวิลด์', 'Central World', 12, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.13.1', 6, 'อินทราสแควร์ประตูน้ำ', 'Indra Square Pratunam', 13, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.14.1', 6, 'ซอยรางน้ำ', 'Rang Nam Allay', 14, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.15.1', 6, 'ตรงข้ามวัดตะพาน', 'Opposite Taphan Temple', 15, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.16.1', 6, 'สำนักงาน ป.ป.ส.', 'ONCB Office', 16, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.17.1', 6, 'รร.พิบูลประชาสรรค์', 'Piboon Prachasan School', 17, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.18.1', 6, 'สถาบันราชานุกูล', 'Rajanukul Institute', 18, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.19.1', 6, 'แยกประชาสงเคราะห์', 'Pracha Songkhro Intersection', 19, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.20.1', 6, 'ประชาสงเคราะห์1', 'Pracha Songkhro 1', 20, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.21.1', 6, 'สำนักงานเคหะดินแดง', 'Dindaeng Housing Office', 21, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.22.1', 6, 'ตลาดดินแดง', 'Dindaeng Market', 22, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.23.1', 6, 'โรงเรียนวชิรศิษฐ์', 'Wichutit School', 23, 'Inbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.24.1', 6, 'ศูนย์บริการสาธารณสุข 4', 'Health Center 4', 24, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.25.1', 6, 'ตรงข้ามโรงเรียนพร้มพรรณวิทยา', 'Opposite Promphanwittaya School', 25, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.26.1', 6, 'ซอยประชาสงเคราะห์21', 'Pracha Songkhro 21', 26, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.27.1', 6, 'ซอยประชาสงเคราะห์23', 'Pracha Songkhro 23', 27, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.28.1', 6, 'วัดพรหมวงศาราม', 'Phrom Wong Saram Temple', 28, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.29.1', 6, 'TVC คอนโดมิเนียม', 'TVC Condominium', 29, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.30.1', 6, 'ตรงข้ามโรงเรียนอำนวย', 'Opposite Amnuayvid School', 30, 'Inbound', 'No');
INSERT INTO Station_stop VALUES ('13.31.1', 6, 'ท่ารถห้วยขวาง', 'Huai Khwang port', 31, 'Inbound', 'Yes');

INSERT INTO Station_stop VALUES ('13.1.2', 6, 'ท่ารถห้วยขวาง', 'Huai Khwang port', 1, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.2.2', 6, 'สถานีดับเพลิงห้วยขวาง, สาธารณสุข52', 'Huai Khwang Fire Station, Public Health 52', 2, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.3.2', 6, 'ตลาดห้วยขวางหลังโรงเรียนสามเสนนอก', 'Huai Khwang Market behind Samsen Nok School', 3, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.4.2', 6, 'ธนาคารกรุงไทยสาขาห้วยขวาง', 'Krungthai Bank Huai Khwang Branch', 4, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.5.2', 6, 'ตรงข้ามทีวีซีคอนโดมิเนียม', 'Opposite TVC Condominium', 5, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.6.2', 6, 'ตรงข้ามวัดพรหมวงศาราม', 'Opposite Phrom Wong Saram Temple', 6, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.7.2', 6, 'ดีดีทาวเวอร์', 'Dd Tower', 7, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.8.2', 6, 'ซอยประชาสงเคราะห์16-18', 'Pracha Songkhro 16-18', 8, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.9.2', 6, 'โรงเรียนพร้มพรรณวิทยา', 'Promphanwittaya School', 9, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.10.2', 6, 'ตรงข้ามศูนย์บริการสาธารณสุข 4', 'Opposite Health Center 4', 10, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.11.2', 6, 'ตรงข้ามโรงเรียนวชิรศิษฐ์', 'Opposite Wichutit School', 11, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.12.2', 6, 'ตรงข้ามตลาดดินแดง', 'Opposite Dindaeng Market', 12, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.13.2', 6, 'ตรงข้ามสำนักงานเคหะดินแดง', 'Opposite the Din Daeng Housing Office', 13, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.14.2', 6, 'ประชาสงเคราะห์2', 'Pracha Songkhro 2', 14, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.15.2', 6, 'แฟลตดินแดง (ป้าย1)', 'Dindaeng Housing (Stop.1)', 15, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.16.2', 6, 'แฟลตดินแดง (ป้าย2)', 'Dindaeng Housing (Stop.2)', 16, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.17.2', 6, 'ตรงข้ามโรงเรียนพิบูลประชาสรรค์', 'Opposite Piboon Prachasan School', 17, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.18.2', 6, 'ตลาดศรีวานิช', 'Sriwanit Market', 18, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.19.2', 6, 'ตรงข้ามซอยรางน้ำ', 'Opposite Rang Nam Allay', 19, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.20.2', 6, 'ตรงข้ามอินทราสแควร์ประตูน้ำ', 'Opposite Indra Square Pratunam', 20, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.21.2', 6, 'บิ๊กซีราชดำริ', 'Big C Rajdamri', 21, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.22.2', 6, 'เพนนินซูลาพลาซ่า', 'Peninsula Plaza', 22, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.23.2', 6, 'BTS ราชดำริ (ทางออก2)', 'BTS Ratchadamri (Exit 2)', 23, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.24.2', 6, 'สถาบันสอนภาษา', 'AUA Language Institute', 24, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.25.2', 6, 'หลังสวน1 อาคารปาร์คเพลส', 'Lang Suan 1, Park Place', 25, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.26.2', 6, 'หลังสวน2', 'Lang Suan 2', 26, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.27.2', 6, 'สมาคมสร้างคุณค่าในประเทศไทย', 'Association of Value Creation in Thailand', 27, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.28.2', 6, 'ซอยพระเจน', 'Phra Chen Allay', 28, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.29.2', 6, 'สวนลุมไนท์บาซาร์', 'Suan Lum Night Bazaar', 29, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.30.2', 6, 'บ่อนกาย', 'Brun Kai', 30, 'Outbound', 'Yes');
INSERT INTO Station_stop VALUES ('13.31.2', 6, 'ตลาดคลองเตย (ถนนสุนทรโกษา ขาออก)', 'Talat Khlong Toei', 31, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.32.2', 6, 'ตรงข้ามสโมสรการท่าเรือ', 'Opposite Port F.C.', 32, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.33.2', 6, 'ตรงข้ามสนามกีฬาการท่าเรือ', 'Opposite Sanamkila Kan Tharuea', 33, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.34.2', 6, 'ซอยคั่วพริก ก่อนถึงแยกกรมศุลกากร', 'Kua Phrik Allay, before Customs Department Intersection', 34, 'Outbound', 'No');
INSERT INTO Station_stop VALUES ('13.35.2', 6, 'อู่คลองเตย', 'Klongtoey Bus Depot', 35, 'Outbound', 'No');
